### ISSUE TITLE
注册页面提交数据之后一直报错

### ISSUE THREAD

**Issue by oodzchen** [nswbmw/N-blog#100]
>/home/lc/node/blog/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;      
              ^
TypeError: undefined is not a function
    at /home/lc/node/blog/routes/index.js:54:9
    at /home/lc/node/blog/models/user.js:75:5
    at /home/lc/node/blog/node_modules/mongodb/lib/mongodb/collection/query.js:164:5
    at Cursor.nextObject (/home/lc/node/blog/node_modules/mongodb/lib/mongodb/cursor.js:753:5)
    at commandHandler (/home/lc/node/blog/node_modules/mongodb/lib/mongodb/cursor.js:727:14)
    at /home/lc/node/blog/node_modules/mongodb/lib/mongodb/db.js:1912:9
    at Server.Base._callHandler (/home/lc/node/blog/node_modules/mongodb/lib/mongodb/connection/base.js:448:41)
    at /home/lc/node/blog/node_modules/mongodb/lib/mongodb/connection/server.js:481:18
    at MongoReply.parseBody (/home/lc/node/blog/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/home/lc/node/blog/node_modules/mongodb/lib/mongodb/connection/server.js:439:20)

完全找不到哪儿出错了

**Comment by kylezhang** [comment]
看情况是这两行：
at /home/lc/node/blog/routes/index.js:54:9
at /home/lc/node/blog/models/user.js:75:5

**Comment by la413972057** [comment]
I think you may have some wrong with your save() function in your user.js
