### ISSUE TITLE
module.js:340 谁遇到了

### ISSUE THREAD

**Issue by Hibettermeatom** [nswbmw/N-blog#108]
module.js:340
    throw err;
    ^

Error: Cannot find module 'serve-favicon'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/tblog/app.js:4:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)

这个提示是怎么处理。

**Comment by hank2015** [comment]
没有安装serve-favicon中间件
