### ISSUE TITLE
博主请看下这个是什么原因

### ISSUE THREAD

**Issue by jsonxu** [nswbmw/N-blog#116]
安装好依赖模块后，打开首页就报错：

/Users/json/project/N-blog/node_modules/connect-mongo/lib/connect-mongo.js:178
          throw err;
                ^
Error: Error connecting to database: failed to connect to [localhost:27017]
    at null.<anonymous> (/Users/json/project/N-blog/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:553:74)
    at emit (events.js:106:17)
    at null.<anonymous> (/Users/json/project/N-blog/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:140:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (/Users/json/project/N-blog/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:512:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickCallback (node.js:419:13)

**Comment by nswbmw** [comment]
连不到 mongodb，可能是：

1. mongodb 没启动
2. connect-mongo 配置没写对

**Comment by hank2015** [comment]
博主，麻烦看一下我的报错"head is not defined"

**Comment by jsonxu** [comment]
谢谢博主，我的芒果DB没有装
