### ISSUE TITLE
转载 的 redirect 功能报错

### ISSUE THREAD

**Issue by zhouxh** [nswbmw/N-blog#124]
我不停的点击 转载 和删除，然后 转载就会报一个错误，服务端出现如下错误并挂掉
D:\cd\workpro\nodejs\nodegit\N-blog\node_modules\mongodb\lib\mongodb\connection\
base.js:246
        throw message;
        ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.header (D:\cd\workpro\nodejs\nodegit\N-blog\node_modules\e
xpress\lib\response.js:666:10)
    at ServerResponse.res.location (D:\cd\workpro\nodejs\nodegit\N-blog\node_mod
ules\express\lib\response.js:780:8)
    at ServerResponse.redirect (D:\cd\workpro\nodejs\nodegit\N-blog\node_modules
\express\lib\response.js:819:8)
    at D:\cd\workpro\nodejs\nodegit\N-blog\routes\index.js:366:13
    at D:\cd\workpro\nodejs\nodegit\N-blog\models\post.js:469:11
    at D:\cd\workpro\nodejs\nodegit\N-blog\node_modules\mongodb\lib\mongodb\coll
ection\core.js:125:9
    at D:\cd\workpro\nodejs\nodegit\N-blog\node_modules\mongodb\lib\mongodb\db.j
s:1179:7
    at D:\cd\workpro\nodejs\nodegit\N-blog\node_modules\mongodb\lib\mongodb\db.j
s:1912:9
    at Server.Base._callHandler (D:\cd\workpro\nodejs\nodegit\N-blog\node_module
s\mongodb\lib\mongodb\connection\base.js:448:41)

**Comment by chenyan940206** [comment]
请问我在登陆时报错，req.flash  is  not a function  ，怎么解决啊？？谢谢

**Comment by nswbmw** [comment]
fixed
