### ISSUE TITLE
第一章的路由控制是不是被搞得太复杂了

### ISSUE THREAD

**Issue by sunqb** [nswbmw/N-blog#125]
直接用express生成的路由控制反而更加容易理解，封装了一层厚反而对新手而言很难理解了。这种路由控制很像ruby的路由控制策略，容易理解的。

**Comment by jeff-ccj** [comment]
同样配置然后提示404
Not Found
404

Error: Not Found
    at /Users/user/Desktop/demo-node/testblog/app.js:19:13
    at Layer.handle [as handle_request] (/Users/user/Desktop/demo-node/testblog/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/user/Desktop/demo-node/testblog/node_modules/express/lib/router/index.js:312:13)
    at /Users/user/Desktop/demo-node/testblog/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/user/Desktop/demo-node/testblog/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/user/Desktop/demo-node/testblog/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/Users/user/Desktop/demo-node/testblog/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/Users/user/Desktop/demo-node/testblog/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/user/Desktop/demo-node/testblog/node_modules/express/lib/router/index.js:312:13)
    at /Users/user/Desktop/demo-node/testblog/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/user/Desktop/demo-node/testblog/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/user/Desktop/demo-node/testblog/node_modules/express/lib/router/index.js:271:10)
    at query (/Users/user/Desktop/demo-node/testblog/node_modules/express/lib/middleware/query.js:49:5)
    at Layer.handle [as handle_request] (/Users/user/Desktop/demo-node/testblog/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/user/Desktop/demo-node/testblog/node_modules/express/lib/router/index.js:312:13)
    at /Users/user/Desktop/demo-node/testblog/node_modules/express/lib/router/index.js:280:7


求解
routes/index.js
=======
var routes = function(app){

    app.get('/', function (req, res) {
        res.render('index', {
            title: '首页'
        });
    });

    app.get('/reg', function (req, res) {
        res.render('reg', {
            title: '用户注册'
        });
    });

    app.get('*', function(req, res){
        res.send('what???', 404);
    });

}

module.exports = routes



app.js

var routes = require('./routes/index');

app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');
app.use(bodyParser.urlencoded({ extended: false }));
app.use(express.static(path.join(__dirname, 'public')));
routes(app)

摘录重要部分代码。。。

**Comment by bill-mark** [comment]
而且安装作者写的路由控制运行会出错 app.set not find

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
