### ISSUE TITLE
mongodb connect closed

### ISSUE THREAD

**Issue by jameswanliu** [nswbmw/N-blog#141]
d:\Documents\Downloads\N-blog-master\N-blog-master\node_modules\connect-mongo\lib\connect-mongo.js:178
          throw err;
          ^

Error: Error connecting to database: connection closed
    at null.<anonymous> (d:\Documents\Downloads\N-blog-master\N-blog-master\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\connection\server.js:605:24)
    at emitNone (events.js:80:13)
    at emit (events.js:179:7)
    at null.<anonymous> (d:\Documents\Downloads\N-blog-master\N-blog-master\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:155:15)
    at emitTwo (events.js:100:13)
    at emit (events.js:185:7)
    at Socket.<anonymous> (d:\Documents\Downloads\N-blog-master\N-blog-master\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\connection\connection.js:528:12)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at TCP._onclose (net.js:475:12)

Process finished with exit code 1

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
