### ISSUE TITLE
第一章提交注册后出错

### ISSUE THREAD

**Issue by dshkwnds** [nswbmw/N-blog#159]
GET /reg 304 14.474 ms - -
GET /stylesheets/style.css 304 2.976 ms - -
/opt/blog/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot set property 'user' of undefined
    at /opt/blog/routes/index.js:34:24
    at /opt/blog/models/user.js:57:17
    at handleCallback (/opt/blog/node_modules/mongodb/lib/utils.js:96:12)
    at /opt/blog/node_modules/mongodb/lib/collection.js:1357:5
    at handleCallback (/opt/blog/node_modules/mongodb/lib/utils.js:96:12)
    at /opt/blog/node_modules/mongodb/lib/cursor.js:661:5
    at handleCallback (/opt/blog/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:159:5)
    at setCursorNotified (/opt/blog/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:511:3)
    at /opt/blog/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:582:16
    at queryCallback (/opt/blog/node_modules/mongodb/node_modules/mongodb-core/lib/cursor.js:220:18)
    at Callbacks.emit (/opt/blog/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at null.messageHandler (/opt/blog/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:358:23)
    at Socket.<anonymous> (/opt/blog/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:292:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)

请老司机指导

**Comment by chesterz184** [comment]
把app.js里的app.use(session...和app.use(flash());放到routes(app);前面试试~

**Comment by yehbeats** [comment]
**保证routes(app);在**
app.use(session({
  secret: settings.cookieSecret,
  key: settings.db,//cookie name
  cookie: {maxAge: 1000 * 60 * 60 * 24 * 30},//30 days
  store: new MongoStore({
    url: 'mongodb://localhost/blog'
  })
}));
app.use(flash());

**之后**

**Comment by nswbmw** [comment]
bingo

教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
