### ISSUE TITLE
Error: Error setting TTL index on collection : sessions

### ISSUE THREAD

**Issue by gzq-studyios** [nswbmw/N-blog#177]
gzqdeiMac:N-blog-master gzq$ node app.js 
Failed to load c++ bson extension, using pure JS version
morgan deprecated morgan(options): use morgan("default", options) instead app.js:27:9
morgan deprecated default format: use combined format app.js:27:9
express-session deprecated undefined resave option; provide resave option app.js:36:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option app.js:36:9
Express server listening on port 3000
/Users/gzq/Pictures/N-blog-master/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:242
        throw message;      
        ^

Error: Error setting TTL index on collection : sessions
    at /Users/gzq/Pictures/N-blog-master/node_modules/connect-mongo/lib/connect-mongo.js:161:23
    at /Users/gzq/Pictures/N-blog-master/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1430:36
    at __executeInsertCommand (/Users/gzq/Pictures/N-blog-master/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1829:12)
    at Db._executeInsertCommand (/Users/gzq/Pictures/N-blog-master/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1930:5)
    at /Users/gzq/Pictures/N-blog-master/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1427:14
    at /Users/gzq/Pictures/N-blog-master/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1560:7
    at /Users/gzq/Pictures/N-blog-master/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/cursor.js:162:16
    at commandHandler (/Users/gzq/Pictures/N-blog-master/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/cursor.js:706:16)
    at /Users/gzq/Pictures/N-blog-master/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1806:9
    at Server.Base._callHandler (/Users/gzq/Pictures/N-blog-master/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:442:41)

**Comment by gzq-studyios** [comment]
使用githubd上面的案例（Express + MongoDB 搭建多人博客），刚开始运行正常，点击转载按钮之后崩溃，之后就连接不上出现错误。

**Comment by liuestc** [comment]
@gzq-studyios 如何解决的？我也遇到这个问题
