### ISSUE TITLE
频繁刷新导致bug404

### ISSUE THREAD

**Issue by newpost** [nswbmw/N-blog#188]
频繁刷新页面报404 具体的错误是：
\N-blog-master\node_modules\mongodb\lib\utils.js:99
    process.nextTick(function() { throw err; });
                                  ^

TypeError: req.next is not a function
    at fn (C:\web\node\N-blog-master\node_modules\express\lib\response.js:899:25
)
    at EventEmitter.app.render (C:\web\node\N-blog-master\node_modules\express\l
ib\application.js:532:5)
    at ServerResponse.res.render (C:\web\node\N-blog-master\node_modules\express
\lib\response.js:904:7)
    at C:\web\node\N-blog-master\routes\index.js:248:13
    at C:\web\node\N-blog-master\models\post.js:97:11
    at handleCallback (C:\web\node\N-blog-master\node_modules\mongodb\lib\utils.
js:96:56)
    at C:\web\node\N-blog-master\node_modules\mongodb\lib\cursor.js:853:16
    at handleCallback (C:\web\node\N-blog-master\node_modules\mongodb\node_modul
es\mongodb-core\lib\cursor.js:172:5)
    at setCursorDeadAndNotified (C:\web\node\N-blog-master\node_modules\mongodb\
node_modules\mongodb-core\lib\cursor.js:507:3)
    at nextFunction (C:\web\node\N-blog-master\node_modules\mongodb\node_modules
\mongodb-core\lib\cursor.js:655:7)

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
