### ISSUE TITLE
config-lite好像有点问题

### ISSUE THREAD

**Issue by Dachow** [nswbmw/N-blog#192]
这两天学您的教程获益匪浅, 谢谢您
今天按4.4启动应用, 发现控制台报错, 输出
```
config-lite load `default` failed                                                                                                       
Error: Cannot find module 'default' from '/home/xiaofen/myblog'                                                                         
    at Function.module.exports [as sync] (/home/xiaofen/myblog/node_modules/.1.1.7@resolve/lib/sync.js:33:11)                           
    at loadConfig (/home/xiaofen/myblog/node_modules/.1.5.0@config-lite/index.js:32:26)                                                 
    at Object.<anonymous> (/home/xiaofen/myblog/node_modules/.1.5.0@config-lite/index.js:18:20) 
```

指定default文件可以正常运行

4.7 routes/signup.js 校验参数 catch (e) {} 代码块中有一个全角引号

**Comment by nswbmw** [comment]
如果是 config-lite 的 bug，欢迎提 pr。全角引号的问题 fix 了，多谢
