### ISSUE TITLE
按照实例做到4.7.3 注册与文件上传 始终报了一个错误

### ISSUE THREAD

**Issue by dicallc** [nswbmw/N-blog#195]
首先辛苦作者贡献了这么基础的教程，博主的书我也买了~

按照教程做到4.7.3 注册与文件上传 始终报了一个错误  我始终不知道为什么

```
"D:\2.ReactNative\5.webstorm11\WebStorm 11.0.3\bin\runnerw.exe" D:\2.ReactNative\1.Node\node.exe index.js
d:\2.ReactNative\work\myblog\node_modules\mongolass\lib\query.js:53
        this[plugin.name] = (...args) => {
                             ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (d:\2.ReactNative\work\myblog\node_modules\mongolass\lib\model.js:7:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (d:\2.ReactNative\work\myblog\node_modules\mongolass\lib\index.js:7:15)
    at Module._compile (module.js:413:34)
```
最后希望博主有空回复一下

**Comment by nswbmw** [comment]
见 https://github.com/nswbmw/N-blog/issues/193

**Comment by dicallc** [comment]
谢谢博主的回复，已解决问题
