### ISSUE TITLE
老大，NODE_ENV不是外部命令

### ISSUE THREAD

**Issue by haocaokai** [nswbmw/N-blog#199]
NODE_ENV=production supervisor --harmony index，到这一步的时候，提示NODE_ENV不是外部或者内部命令，是windows不支持NODE_ENV吗？用了网上传的set NODE_ENV=production似乎也不行，请问有什么方法吗？

**Comment by nswbmw** [comment]
用 `set NODE_ENV=production` 是可以的。你在 REPL 中试试 `process.env.production`

**Comment by haocaokai** [comment]
set NODE_ENV=production是在命令行中输入吗？输入后没反应，

**Comment by nswbmw** [comment]
没反应，但是设置成功了

**Comment by haocaokai** [comment]
![12](https://cloud.githubusercontent.com/assets/16473565/20163155/3335d304-a735-11e6-9a4d-5525ec0d3540.png)

**Comment by nswbmw** [comment]
```
set NODE_ENV=production
supervisor --harmoy index
```

**Comment by haocaokai** [comment]
![12](https://cloud.githubusercontent.com/assets/16473565/20163520/273f582e-a738-11e6-90f3-f49279decffb.png)

**Comment by nswbmw** [comment]
贴出 `myblog/lib/mongo.js`

**Comment by haocaokai** [comment]
`var config = require('config-lite');
var Mongolass = require('mongolass');
var mongolass = new Mongolass();
mongolass.connect(config.mongodb);

var moment = require('moment');
var objectIdToTimestamp = require('objectid-to-timestamp');

exports.User = mongolass.model('User', {
	name : {type : 'string'},
	password : {type : 'string'},
	avatar : {type : 'string'},
	gender: { type: 'string', enum: ['m', 'f', 'x'] },
  	bio: { type: 'string' }
});

// 根据 id 生成创建时间 created_at
mongolass.plugin('addCreatedAt', {
  afterFind: function (results) {
    results.forEach(function (item) {
      item.created_at = moment(objectIdToTimestamp(item._id)).format('YYYY-MM-DD HH:mm');
    });
    return results;
  },
  afterFindOne: function (result) {
    if (result) {
      result.created_at = moment(objectIdToTimestamp(result._id)).format('YYYY-MM-DD HH:mm');
    }
    return result;
  }
});

exports.Post = mongolass.model('Post', {
  author: { type: Mongolass.Types.ObjectId },
  title: { type: 'string' },
  content: { type: 'string' },
  pv: { type: 'number' }
});
// 按创建时间降序查看用户的文章列表
exports.Post.index({ author: 1, _id: -1 }).exec();


exports.Comment = mongolass.model('Comment', {
  author: { type: Mongolass.Types.ObjectId },
  content: { type: 'string' },
  postId: { type: Mongolass.Types.ObjectId }
});
exports.Post.index({ postId: 1, _id: 1 }).exec();// 通过文章 id 获取该文章下所有留言，按留言创建时间升序
exports.Post.index({ author: 1, _id: 1 }).exec();// 通过用户 id 和留言 id 删除一个留言`

**Comment by nswbmw** [comment]
mongodb 起了吗

**Comment by haocaokai** [comment]
![image](https://cloud.githubusercontent.com/assets/16473565/20163892/229302e6-a73b-11e6-8bf8-9d06a1444ba5.png)

起了，按照您的步骤：
1、添加："start": "NODE_ENV=production pm2 start index.js --node-args='--harmony' --name 'myblog'"
2、set NODE_ENV=production
3、supervisor --harmoy index
4、就出现这个
![image](https://cloud.githubusercontent.com/assets/16473565/20163905/3be7b944-a73b-11e6-815a-0a644e651972.png)

**Comment by nswbmw** [comment]
你 mongodb 加了 auth  了吧。配置里改下

**Comment by haocaokai** [comment]
![image](https://cloud.githubusercontent.com/assets/16473565/20164214/b691a612-a73d-11e6-994e-687e31ba68e8.png)
meiyou 加呀，完全是按照您书上写的

**Comment by nswbmw** [comment]
你 production.js 文件贴下

**Comment by haocaokai** [comment]
module.exports = {
  mongodb: 'mongodb://myblog:caokai@ds139937.mlab.com:39937/myblog'
};
就这一句

**Comment by nswbmw** [comment]
1. 检查用户名密码是否正确
2. mlab 的这个用户是否是可写的，你改成教程里的这个试试 `mongodb://myblog:myblog@ds139327.mlab.com:39327/myblog`

**Comment by haocaokai** [comment]
嗯，我想起来了，我设置的时候设置的是只读的，是不是跟这个有关系？

**Comment by nswbmw** [comment]
应该就是这个问题，你创建个可写的用户试试

**Comment by haocaokai** [comment]
![image](https://cloud.githubusercontent.com/assets/16473565/20166531/61065ea0-a750-11e6-93d4-733b32d67beb.png)
我重新创建下试试

**Comment by haocaokai** [comment]
您好，不好意思又打扰了，我没有用命令行，我是直接连接github地址部署的，https://caokai.herokuapp.com/，
部署好后，页面无法打开，以下是部署heroku的部署log

-----> Node.js app detected
-----> Creating runtime environment

   NPM_CONFIG_LOGLEVEL=error
   NPM_CONFIG_PRODUCTION=true
   NODE_ENV=production
   NODE_MODULES_CACHE=true
-----> Installing binaries
engines.node (package.json): unspecified
engines.npm (package.json): unspecified (use default)

   Resolving node version (latest stable) via semver.io...
   Downloading and installing node 5.11.1...
   Using default npm version: 3.8.6
-----> Restoring cache
Loading 2 from cacheDirectories (default):
- node_modules
- bower_components (not cached - skipping)
-----> Building dependencies
Installing node modules (package.json)
-----> Caching build
Clearing previous node cache
Saving 2 cacheDirectories (default):
- node_modules
- bower_components (nothing to cache)
-----> Build succeeded!
├── config-lite@1.5.0
├── connect-flash@0.1.1
├── connect-mongo@1.3.2
├── ejs@2.5.2
├── express@4.14.0
├── express-formidable@1.0.0
├── express-session@1.14.2
├── express-winston@2.0.0
├── marked@0.3.6
├── mocha@3.1.2
├── moment@2.15.2
├── mongolass@2.3.2
├── objectid-to-timestamp@1.3.0
├── sha1@1.1.1
├── supertest@2.0.1
└── winston@2.3.0

-----> Discovering process types
Procfile declares types -> web
-----> Compressing...
Done: 15.8M
-----> Launching...
Released v8
https://caokai.herokuapp.com/ deployed to Heroku

![image](https://cloud.githubusercontent.com/assets/16473565/20168758/c58dad70-a75e-11e6-82f8-f38dbc49a0d9.png)
最后也显示构建完成了。不解~~

**Comment by nswbmw** [comment]
我记得可以去 heroku 上看日志的，这样我也看不出来

**Comment by haocaokai** [comment]
2016-11-10T08:23:19.080133+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-11-10T08:23:19.080134+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/mongolass/lib/index.js:7:15)
2016-11-10T08:23:19.080134+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-11-10T08:23:19.178450+00:00 heroku[web.1]: State changed from starting to crashed
2016-11-10T08:23:19.170585+00:00 heroku[web.1]: Process exited with status 1
2016-11-10T08:23:20.206980+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=caokai.herokuapp.com request_id=ee4f4797-61d9-4795-be83-b10975017914 fwd="45.76.199.161" dyno= connect= service= status=503 bytes=
2016-11-10T08:23:21.329234+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=caokai.herokuapp.com request_id=d060c60b-2c8a-4fb6-997e-86b757ed738f fwd="45.76.199.161" dyno= connect= service= status=503 bytes=
2016-11-10T08:32:00.166687+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=caokai.herokuapp.com request_id=401353c3-e766-4bc4-a404-8cc8735221d3 fwd="45.32.13.199" dyno= connect= service= status=503 bytes=
2016-11-10T08:32:01.814182+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=caokai.herokuapp.com request_id=51dfcd0c-799c-46a7-b068-d307dfbe61f0 fwd="45.32.13.199" dyno= connect= service= status=503 bytes=
2016-11-10T08:37:26.234457+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=caokai.herokuapp.com request_id=197fad1f-5e77-4271-91e6-5e16a5bd6890 fwd="124.42.102.140" dyno= connect= service= status=503 bytes=
2016-11-10T08:37:26.863536+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=caokai.herokuapp.com request_id=4a2c2c39-d5b6-4da4-93c3-b65162e3ac0b fwd="124.42.102.140" dyno= connect= service= status=503 bytes=

**Comment by nswbmw** [comment]
你这日志不全啊。。这段上面的呢

**Comment by haocaokai** [comment]
又来麻烦你了，我觉得部署有问题应该是注册的原因。

注册完成后，数据库里完成了注册，已经有数据了，本地public > img里却上传了两个头像，且域名正确的情况下，无法跳转到首页显示注册成功，采用本地数据库时，这些操作都是正确的，切换到线上数据库出错
![image](https://cloud.githubusercontent.com/assets/16473565/20201520/b9cd77a0-a7f3-11e6-8f6d-72d0bb045e97.png)

**Comment by haocaokai** [comment]
2016-11-11T02:48:00.047065+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-11-11T02:48:00.047066+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-11-11T02:48:00.047066+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-11-11T02:48:00.047070+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-11-11T02:48:00.047071+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-11-11T02:48:00.047071+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-11-11T02:48:00.047072+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/mongolass/lib/index.js:7:15)
2016-11-11T02:48:00.047073+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-11-11T02:48:00.145428+00:00 heroku[web.1]: Process exited with status 1
2016-11-11T02:48:00.159534+00:00 heroku[web.1]: State changed from starting to crashed
2016-11-11T02:48:20.513235+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=caokai.herokuapp.com request_id=c0fc9178-18ee-467f-9c9c-a3c94ac089c9 fwd="124.42.102.140" dyno= connect= service= status=503 bytes=
2016-11-11T02:48:45.907568+00:00 heroku[api]: Deploy 78a2695 by 307356224@qq.com
2016-11-11T02:48:45.907667+00:00 heroku[api]: Release v5 created by 307356224@qq.com
2016-11-11T02:48:46.082410+00:00 heroku[slug-compiler]: Slug compilation started
2016-11-11T02:48:46.082428+00:00 heroku[slug-compiler]: Slug compilation finished
2016-11-11T02:48:46.182229+00:00 heroku[web.1]: State changed from crashed to starting
2016-11-11T02:48:48.441533+00:00 heroku[web.1]: Starting process with command `node index.js`
2016-11-11T02:48:51.651630+00:00 app[web.1]: Fri, 11 Nov 2016 02:48:51 GMT express-session deprecated undefined resave option; provide resave option at index.js:23:9
2016-11-11T02:48:51.652387+00:00 app[web.1]: Fri, 11 Nov 2016 02:48:51 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at index.js:23:9
2016-11-11T02:48:51.765775+00:00 app[web.1]: /app/node_modules/mongolass/lib/query.js:53
2016-11-11T02:48:51.765777+00:00 app[web.1]:         this[plugin.name] = (...args) => {
2016-11-11T02:48:51.765778+00:00 app[web.1]:                              ^^^
2016-11-11T02:48:51.765779+00:00 app[web.1]: 
2016-11-11T02:48:51.765779+00:00 app[web.1]: SyntaxError: Unexpected token ...
2016-11-11T02:48:51.765780+00:00 app[web.1]:     at exports.runInThisContext (vm.js:53:16)
2016-11-11T02:48:51.765780+00:00 app[web.1]:     at Module._compile (module.js:387:25)
2016-11-11T02:48:51.765781+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-11-11T02:48:51.765782+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-11-11T02:48:51.765783+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-11-11T02:48:51.765783+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-11-11T02:48:51.765784+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-11-11T02:48:51.765785+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/mongolass/lib/model.js:7:15)
2016-11-11T02:48:51.765786+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-11-11T02:48:51.765786+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-11-11T02:48:51.765787+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-11-11T02:48:51.765788+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-11-11T02:48:51.765788+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-11-11T02:48:51.765789+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-11-11T02:48:51.765790+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/mongolass/lib/index.js:7:15)
2016-11-11T02:48:51.765795+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-11-11T02:48:51.817407+00:00 heroku[web.1]: State changed from starting to crashed
2016-11-11T02:48:51.830394+00:00 heroku[web.1]: Process exited with status 1

这应该是最全的了

**Comment by nswbmw** [comment]
```
2016-11-11T02:48:51.765777+00:00 app[web.1]: this[plugin.name] = (...args) => {
2016-11-11T02:48:51.765778+00:00 app[web.1]: ^^^
2016-11-11T02:48:51.765779+00:00 app[web.1]: 
2016-11-11T02:48:51.765779+00:00 app[web.1]: SyntaxError: Unexpected token ...
```

开启 `--harmony`

**Comment by haocaokai** [comment]
那问题应该就还是在服务器启动上
我安装了cross后，输入命令无效
![image](https://cloud.githubusercontent.com/assets/16473565/20202915/12f48ed6-a7fe-11e6-8eda-7769c70a6f3a.png)

后来我又在这里加入corss-env试了试，
![image](https://cloud.githubusercontent.com/assets/16473565/20202928/41c54782-a7fe-11e6-9ffd-7cd251b04aa9.png)

输入以下两句命令
![image](https://cloud.githubusercontent.com/assets/16473565/20202941/653a5c8e-a7fe-11e6-95a4-95524318fbba.png)

服务器确实是开启了，运行网页也没有问题
![image](https://cloud.githubusercontent.com/assets/16473565/20202962/805dc244-a7fe-11e6-8888-adf2d8a14cd4.png)

但接着就报错
![image](https://cloud.githubusercontent.com/assets/16473565/20202974/950541ae-a7fe-11e6-8c6b-0bd28ddefb9c.png)

我看能运行就没管他，直接上传的

**Comment by nswbmw** [comment]
全局安装 cross-env 啊。。

**Comment by haocaokai** [comment]
全局安装后，依然有如上错误，之前网页能打开是幻觉，3000端口被占用了， 一直未关闭。

**Comment by nswbmw** [comment]
哦。。用 `pm2 l` 看，应该之前 pm2 起的，用 `pm2 delete all` 删除，然后 `npm start` 再起

**Comment by haocaokai** [comment]
heroku的日志还跟原来一样，查了下，没有ssh秘钥，跟这个有关系吗？
![image](https://cloud.githubusercontent.com/assets/16473565/20205518/8131af94-a814-11e6-8eff-0c87aa3fe145.png)

**Comment by nswbmw** [comment]
换 ucloud 试试吧

**Comment by haocaokai** [comment]
悲剧呀~~

**Comment by haocaokai** [comment]
不好意思再提问下，跟缺少SSH秘钥有关吗？
![image](https://cloud.githubusercontent.com/assets/16473565/20206894/964f1790-a81e-11e6-9e22-250a64638af3.png)

**Comment by nswbmw** [comment]
这个我也不清楚了（好久不用 heroku 了，你 google 下

**Comment by haocaokai** [comment]
好的，谢谢回答这么多低级问题

**Comment by haocaokai** [comment]
老大不好意思又来麻烦你了，最后一步还是不想放弃。
![1](https://cloud.githubusercontent.com/assets/16473565/20251191/068ade42-aa52-11e6-95d1-e7ab32fdbbba.png)

您看下这个日志，上面显示key这里错误，但这里我都是按照您书上写的，应该不会有错误啊

![2](https://cloud.githubusercontent.com/assets/16473565/20251238/c726cec2-aa52-11e6-95fc-f5199d2c4bc2.png)

**Comment by nswbmw** [comment]
1. 你在这个 app.use 前打印下 config
2. 看看 config/default.js 是否有 session 的配置

**Comment by cody1991** [comment]
`2016-11-20T11:13:19.476344+00:00 heroku[web.1]: State changed from crashed to starting
2016-11-20T11:13:21.085118+00:00 heroku[web.1]: Starting process with command `npm start`
2016-11-20T11:13:23.287499+00:00 heroku[web.1]: State changed from starting to crashed
2016-11-20T11:13:23.164883+00:00 app[web.1]: 
2016-11-20T11:13:23.164903+00:00 app[web.1]: > codyblog@1.0.0 start /app
2016-11-20T11:13:23.164904+00:00 app[web.1]: > NODE_ENV=production pm2 start index.js --node-args='--harmony' --name 'codyblog'
2016-11-20T11:13:23.164905+00:00 app[web.1]: 
2016-11-20T11:13:23.169490+00:00 app[web.1]: sh: 1: pm2: not found
2016-11-20T11:13:23.173896+00:00 app[web.1]: 
2016-11-20T11:13:23.181071+00:00 app[web.1]: npm ERR! Linux 3.13.0-100-generic
2016-11-20T11:13:23.181398+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2016-11-20T11:13:23.181557+00:00 app[web.1]: npm ERR! node v5.11.1
2016-11-20T11:13:23.181900+00:00 app[web.1]: npm ERR! npm  v3.8.6
2016-11-20T11:13:23.182134+00:00 app[web.1]: npm ERR! file sh
2016-11-20T11:13:23.182284+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2016-11-20T11:13:23.182422+00:00 app[web.1]: npm ERR! errno ENOENT
2016-11-20T11:13:23.182574+00:00 app[web.1]: npm ERR! syscall spawn
2016-11-20T11:13:23.182693+00:00 app[web.1]: npm ERR! codyblog@1.0.0 start: `NODE_ENV=production pm2 start index.js --node-args='--harmony' --name 'codyblog'`
2016-11-20T11:13:23.182808+00:00 app[web.1]: npm ERR! spawn ENOENT
2016-11-20T11:13:23.182928+00:00 app[web.1]: npm ERR! 
2016-11-20T11:13:23.183044+00:00 app[web.1]: npm ERR! Failed at the codyblog@1.0.0 start script 'NODE_ENV=production pm2 start index.js --node-args='--harmony' --name 'codyblog''.
2016-11-20T11:13:23.183156+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2016-11-20T11:13:23.183275+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the codyblog package,
2016-11-20T11:13:23.183385+00:00 app[web.1]: npm ERR! not with npm itself.
2016-11-20T11:13:23.183599+00:00 app[web.1]: npm ERR!     NODE_ENV=production pm2 start index.js --node-args='--harmony' --name 'codyblog'
2016-11-20T11:13:23.183492+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2016-11-20T11:13:23.183709+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2016-11-20T11:13:23.183818+00:00 app[web.1]: npm ERR!     npm bugs codyblog
2016-11-20T11:13:23.183926+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2016-11-20T11:13:23.184035+00:00 app[web.1]: npm ERR!     npm owner ls codyblog
2016-11-20T11:13:23.184154+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2016-11-20T11:13:23.187706+00:00 app[web.1]: 
2016-11-20T11:13:23.187887+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2016-11-20T11:13:23.187990+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2016-11-20T11:13:23.271714+00:00 heroku[web.1]: Process exited with status 1
2016-11-20T11:13:35.257954+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=codyblog.herokuapp.com request_id=1eae2710-bf0c-493d-b03a-a07e5f65156b fwd="45.32.49.66" dyno= connect= service= status=503 bytes=`

请问这个问题？。。

**Comment by nswbmw** [comment]
```
2016-11-20T11:13:23.169490+00:00 app[web.1]: sh: 1: pm2: not found
```

先全局装 pm2

**Comment by cody1991** [comment]
这个是heroku logs显示的。。我后面把配置文件改成 node index.js的

然后发现 heroku logs 显示的错误是  let const class 这些前面必须写 use strict。。不支持es6嘛

**Comment by nswbmw** [comment]
那你就加 `use strict` 啊。。我看 node 是 v5.11.1，支持的

**Comment by cody1991** [comment]
“我看 node 是 v5.11.1，支持的”。。所以我很纠结～

谢谢啦，我再看看

**Comment by lakeylee** [comment]
\node_modules\mongolass\lib\query.js:54
        this[plugin.name] = (...args) => {
                             ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\lakey\Project\study\nodejs\app_mysql\node_modules\mongolass\lib\model.js:7:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by lakeylee** [comment]
mongolass 报错！
mongodb-win32-x86_64-2008plus-ssl-3.2.12-70-g0608260

**Comment by shawn-jdd** [comment]
@haocaokai node没安装成全局的吧
