### ISSUE TITLE
4.9.2发表文章时报错

### ISSUE THREAD

**Issue by Zaynex** [nswbmw/N-blog#203]
```
Error
   at Model.insert (D:\GitHub\nblog\node_modules\mongolass\lib\query.js:107:16)
   at Object.create (D:\GitHub\nblog\models\posts.js:23:17)
   at D:\GitHub\nblog\routes\posts.js:53:12
   at Layer.handle [as handle_request] (D:\GitHub\nblog\node_modules\express\lib\router\layer.js:95:5)
   at next (D:\GitHub\nblog\node_modules\express\lib\router\route.js:131:13)
   at checkLogin (D:\GitHub\nblog\middlewares\check.js:7:3)
   at Layer.handle [as handle_request] (D:\GitHub\nblog\node_modules\express\lib\router\layer.js:95:5)
   at next (D:\GitHub\nblog\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (D:\GitHub\nblog\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (D:\GitHub\nblog\node_modules\express\lib\router\layer.js:95:5)
   at D:\GitHub\nblog\node_modules\express\lib\router\index.js:277:22
   at Function.process_params (D:\GitHub\nblog\node_modules\express\lib\router\index.js:330:12)
   at next (D:\GitHub\nblog\node_modules\express\lib\router\index.js:271:10)
   at Function.handle (D:\GitHub\nblog\node_modules\express\lib\router\index.js:176:3)
   at router (D:\GitHub\nblog\node_modules\express\lib\router\index.js:46:12)
   at Layer.handle [as handle_request] (D:\GitHub\nblog\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (D:\GitHub\nblog\node_modules\express\lib\router\index.js:312:13)
   at D:\GitHub\nblog\node_modules\express\lib\router\index.js:280:7
   at Function.process_params (D:\GitHub\nblog\node_modules\express\lib\router\index.js:330:12)
   at next (D:\GitHub\nblog\node_modules\express\lib\router\index.js:271:10)
   at D:\GitHub\nblog\index.js:57:2
   at Layer.handle [as handle_request] (D:\GitHub\nblog\node_modules\express\lib\router\layer.js:95:5)
```

登录注册没问题，点击个人主页也没有问题。
报错之后我也尝试清除数据库重新注册，结果依然是这个问题，求教育。

**Comment by nswbmw** [comment]
错误栈很明确了啊，看：

```
at Object.create (D:\GitHub\nblog\models\posts.js:23:17)
at D:\GitHub\nblog\routes\posts.js:53:12
```

如果还是没发现问题，贴出相关代码 models\posts.js， routes\posts.js

**Comment by Zaynex** [comment]
嗯，看到了提示，感觉是这个`post`参数的问题，代码如下

###  models/posts.js
```js
var marked = require('marked');
var Post = require('../lib/mongo').Post;

// 将 post 的 content 从 markdown 转换成 html
Post.plugin('contentToHtml', {
  afterFind: function (posts) {
    return posts.map(function (post) {
      post.content = marked(post.content);
      return post;
    });
  },
  afterFindOne: function (post) {
    if (post) {
      post.content = marked(post.content);
    }
    return post;
  }
});

module.exports = {
  // 创建一篇文章
  create: function create(post) {
    return Post.create(post).exec();
  },

  // 通过文章 id 获取一篇文章
  getPostById: function getPostById(postId) {
    return Post
      .findOne({ _id: postId })
      .populate({ path: 'author', model: 'User' })
      .addCreatedAt()
      .contentToHtml()
      .exec();
  },

  // 按创建时间降序获取所有用户文章或者某个特定用户的所有文章
  getPosts: function getPosts(author) {
    var query = {};
    if (author) {
      query.author = author;
    }
    return Post
      .find(query)
      .populate({ path: 'author', model: 'User' })
      .sort({ _id: -1 })
      .addCreatedAt()
      .contentToHtml()
      .exec();
  },

  // 通过文章 id 给 pv 加 1
  incPv: function incPv(postId) {
    return Post
      .update({ _id: postId }, { $inc: { pv: 1 } })
      .exec();
  }
};
```

### routes/posts.js
```
var express = require("express");
var router = express.Router();
var PostModel = require('../models/posts');

//载入验证中间件
var checkLogin = require("../middlewares/check").checkLogin;


// GET/ posts 所有用户或特定用户的文章页
// GET /posts?author=xxx
router.get("/", function (req, res, next) {
	var author = req.query.author;

	PostModel.getPosts(author)
		.then(function(posts){
			res.render("posts", {
				posts: posts
			});
		})
		.catch(next);
});


// GET /posts/create 发表文章页
router.get('/create', checkLogin, function(req, res, next){
	res.render("create");
});

//发布一篇文章
router.post('/', checkLogin, function(req, res, next){
	var author = req.session.user._id;
	var title = req.fields.title;
	var content = req.fields.content;
	try{
		if(!title.length){
			throw new Error('请填写标题');
		}
		if(!content.length){
			throw new Error("请填写内容");
		}
	}catch(e){
		req.flash('error', e.message);
		return res.redirect('back');
	}

	var post = {
		author: author,
		title: title,
		content: content,
		pv: 0
	};

	PostModel.create(post).then(function(result){
		// 此 post 是插入 mongodb 后的值，包含 _id
		post = result.ops[0];
		req.flash('success', '发表成功');
		//跳转后发布到该文章页
		res.redirect(`/posts/${post._id}`);
	}).catch(next);
});

module.exports = router;
```

**Comment by nswbmw** [comment]
```
}catch(e){
        req.flash('error', e.message);
        return res.redirect('back');
    }
```

req.flash('error', e.message); 应该返回错误信息了吧，或者在 catch 里打印下 e：

```
console.log(e)
console.log(e.stack)
```

**Comment by Zaynex** [comment]
我加了代码
```
try{
		if(!title.length){
			throw new Error('请填写标题');
		}
		if(!content.length){
			throw new Error("请填写内容");
		}
	}catch(e){
		console.log(e);
		console.log(e.stack);
		req.flash('error', e.message);
		return res.redirect('back');

	}
```
报错信息还是和原来一样
```
Error
    at Model.insert (D:\GitHub\nblog\node_modules\mongolass\lib\query.js:107:16)
    at Object.create (D:\GitHub\nblog\models\posts.js:23:17)
    at D:\GitHub\nblog\routes\posts.js:56:12
    at Layer.handle [as handle_request] (D:\GitHub\nblog\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\GitHub\nblog\node_modules\express\lib\router\route.js:131:13)
    at checkLogin (D:\GitHub\nblog\middlewares\check.js:7:3)
    at Layer.handle [as handle_request] (D:\GitHub\nblog\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\GitHub\nblog\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (D:\GitHub\nblog\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\GitHub\nblog\node_modules\express\lib\router\layer.js:95:5)
    at D:\GitHub\nblog\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (D:\GitHub\nblog\node_modules\express\lib\router\index.js:330:12)
    at next (D:\GitHub\nblog\node_modules\express\lib\router\index.js:271:10)
    at Function.handle (D:\GitHub\nblog\node_modules\express\lib\router\index.js:176:3)
    at router (D:\GitHub\nblog\node_modules\express\lib\router\index.js:46:12)
    at Layer.handle [as handle_request] (D:\GitHub\nblog\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\GitHub\nblog\node_modules\express\lib\router\index.js:312:13)
    at D:\GitHub\nblog\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (D:\GitHub\nblog\node_modules\express\lib\router\index.js:330:12)
    at next (D:\GitHub\nblog\node_modules\express\lib\router\index.js:271:10)
    at D:\GitHub\nblog\index.js:57:2
    at Layer.handle [as handle_request] (D:\GitHub\nblog\node_modules\express\lib\router\layer.js:95:5)

```

**Comment by nswbmw** [comment]
额。。我错了，加错地方了。

```
PostModel.create(post).then(function(result){
    // 此 post 是插入 mongodb 后的值，包含 _id
    post = result.ops[0];
    req.flash('success', '发表成功');
    //跳转后发布到该文章页
    res.redirect(`/posts/${post._id}`);
}).catch(next);
```

改成

```
PostModel.create(post).then(function(result){
    // 此 post 是插入 mongodb 后的值，包含 _id
    post = result.ops[0];
    req.flash('success', '发表成功');
    //跳转后发布到该文章页
    res.redirect(`/posts/${post._id}`);
}).catch(e => {
  console.log(e)
  console.log(e.stack)
  next(e);
});
```

**Comment by Zaynex** [comment]
```
{ [Error: ($.title: "我去啊") ✖ (type: String)]
  validator: 'type',
  actual: '我去啊',
  expected: { type: 'String' },
  path: '$.title',
  schema: 'PostSchema',
  model: 'Post',
  plugin: 'MongolassSchema',
  type: 'beforeInsert',
  args: [] }
Error
    at Model.insert (D:\GitHub\nblog\node_modules\mongolass\lib\query.js:107:16)
    at Object.create (D:\GitHub\nblog\models\posts.js:23:17)
    at D:\GitHub\nblog\routes\posts.js:54:12
    at Layer.handle [as handle_request] (D:\GitHub\nblog\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\GitHub\nblog\node_modules\express\lib\router\route.js:131:13)
    at checkLogin (D:\GitHub\nblog\middlewares\check.js:7:3)
    at Layer.handle [as handle_request] (D:\GitHub\nblog\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\GitHub\nblog\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (D:\GitHub\nblog\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\GitHub\nblog\node_modules\express\lib\router\layer.js:95:5)
    at D:\GitHub\nblog\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (D:\GitHub\nblog\node_modules\express\lib\router\index.js:330:12)
    at next (D:\GitHub\nblog\node_modules\express\lib\router\index.js:271:10)
    at Function.handle (D:\GitHub\nblog\node_modules\express\lib\router\index.js:176:3)
    at router (D:\GitHub\nblog\node_modules\express\lib\router\index.js:46:12)
    at Layer.handle [as handle_request] (D:\GitHub\nblog\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\GitHub\nblog\node_modules\express\lib\router\index.js:312:13)
    at D:\GitHub\nblog\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (D:\GitHub\nblog\node_modules\express\lib\router\index.js:330:12)
    at next (D:\GitHub\nblog\node_modules\express\lib\router\index.js:271:10)
    at D:\GitHub\nblog\index.js:57:2
    at Layer.handle [as handle_request] (D:\GitHub\nblog\node_modules\express\lib\router\layer.js:95:5)
Error
    at Model.insert (D:\GitHub\nblog\node_modules\mongolass\lib\query.js:107:16)
    at Object.create (D:\GitHub\nblog\models\posts.js:23:17)
    at D:\GitHub\nblog\routes\posts.js:54:12
    at Layer.handle [as handle_request] (D:\GitHub\nblog\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\GitHub\nblog\node_modules\express\lib\router\route.js:131:13)
    at checkLogin (D:\GitHub\nblog\middlewares\check.js:7:3)
    at Layer.handle [as handle_request] (D:\GitHub\nblog\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\GitHub\nblog\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (D:\GitHub\nblog\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\GitHub\nblog\node_modules\express\lib\router\layer.js:95:5)
    at D:\GitHub\nblog\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (D:\GitHub\nblog\node_modules\express\lib\router\index.js:330:12)
    at next (D:\GitHub\nblog\node_modules\express\lib\router\index.js:271:10)
    at Function.handle (D:\GitHub\nblog\node_modules\express\lib\router\index.js:176:3)
    at router (D:\GitHub\nblog\node_modules\express\lib\router\index.js:46:12)
    at Layer.handle [as handle_request] (D:\GitHub\nblog\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\GitHub\nblog\node_modules\express\lib\router\index.js:312:13)
    at D:\GitHub\nblog\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (D:\GitHub\nblog\node_modules\express\lib\router\index.js:330:12)
    at next (D:\GitHub\nblog\node_modules\express\lib\router\index.js:271:10)
    at D:\GitHub\nblog\index.js:57:2
    at Layer.handle [as handle_request] (D:\GitHub\nblog\node_modules\express\lib\router\layer.js:95:5)

```

感谢，原来是我model类型定义出错了，已经找到错误并改正了。现在返回的是，应该是没问题了
```
http://localhost:3000/posts/582a83ea60563e1a1c0a5e6b
```
