### ISSUE TITLE
添加了mongo.js之后，在users.js当中引用mongo.js并定义添加方法之后报错

### ISSUE THREAD

**Issue by mawenge** [nswbmw/N-blog#217]
`var User = require('../lib/mongo').User;

module.exports = {
    // 注册一个用户
    create: function create(user) {
        return User.create(user).exec();
    }
};`

应该是执行上面的代码的时候出现
`D:\nodeExample\myblog>node index.js
express-session deprecated undefined resave option; provide resave option index.js:19:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option index.js:19:9
D:\nodeExample\myblog\node_modules\mongolass\lib\query.js:53
        this[plugin.name] = (...args) => {
                             ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\nodeExample\myblog\node_modules\mongolass\lib\model.js:7:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\nodeExample\myblog\node_modules\mongolass\lib\index.js:7:15)
    at Module._compile (module.js:409:26)

`
代码已经提交到github上面了 https://github.com/mawenge/myblog，在win7环境下开发

**Comment by mawenge** [comment]
已经解决了，把node.js的版本从4.x.x升级到最新版本就没有问题了
