### ISSUE TITLE
config-lite load `development` failed

### ISSUE THREAD

**Issue by Yang9322** [nswbmw/N-blog#219]
请问一下，将项目clone到本地之后然后进行npm install，再运行就报这个错误，是什么情况导致的呢，我是初学Node.JS的，非常感谢
config-lite load `development` failed
Error: Cannot find module 'development' from '/Users/heyang/N-blog'
    at Function.module.exports [as sync] (/Users/heyang/N-blog/node_modules/config-lite/node_modules/resolve/lib/sync.js:33:11)
    at loadConfig (/Users/heyang/N-blog/node_modules/config-lite/index.js:32:26)
    at Object.<anonymous> (/Users/heyang/N-blog/node_modules/config-lite/index.js:18:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/heyang/N-blog/index.js:6:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.runMain [as _onTimeout] (module.js:441:10)
    at Timer.listOnTimeout (timers.js:92:15)
Sun, 27 Nov 2016 07:52:11 GMT express-session deprecated undefined resave option; provide resave option at index.js:22:9
Sun, 27 Nov 2016 07:52:11 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at index.js:22:9

**Comment by nswbmw** [comment]
有 config/development.js 配置文件吗

**Comment by Yang9322** [comment]
自己搞定啦，多谢多谢

发自我的 iPhone

**Comment by nswbmw** [comment]
@Yang9322 什么问题，说明下？
