### ISSUE TITLE
4.7注册 出现Error: invalid schema, expected mongodb

### ISSUE THREAD

**Issue by sinchang** [nswbmw/N-blog#227]
报错如下：
```
Error: invalid schema, expected mongodb
    at module.exports (/Users/sinchang/Desktop/node-notes/node_modules/.2.2.11@mongodb/lib/url_parser.js:20:11)
    at connect (/Users/sinchang/Desktop/node-notes/node_modules/.2.2.11@mongodb/lib/mongo_client.js:290:16)
    at /Users/sinchang/Desktop/node-notes/node_modules/.2.2.11@mongodb/lib/mongo_client.js:106:7
    at Function.MongoClient.connect (/Users/sinchang/Desktop/node-notes/node_modules/.2.2.11@mongodb/lib/mongo_client.js:105:12)
    at Mongolass.connect (/Users/sinchang/Desktop/node-notes/node_modules/.2.3.2@mongolass/lib/index.js:47:8)
    at Object.<anonymous> (/Users/sinchang/Desktop/node-notes/lib/mongo.js:7:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sinchang/Desktop/node-notes/models/users.js:5:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
Error: invalid schema, expected mongodb
    at module.exports (/Users/sinchang/Desktop/node-notes/node_modules/.2.2.11@mongodb/lib/url_parser.js:20:11)
    at connect (/Users/sinchang/Desktop/node-notes/node_modules/.2.2.11@mongodb/lib/mongo_client.js:290:16)
    at /Users/sinchang/Desktop/node-notes/node_modules/.2.2.11@mongodb/lib/mongo_client.js:106:7
    at Function.MongoClient.connect (/Users/sinchang/Desktop/node-notes/node_modules/.2.2.11@mongodb/lib/mongo_client.js:105:12)
    at Mongolass.connect (/Users/sinchang/Desktop/node-notes/node_modules/.2.3.2@mongolass/lib/index.js:47:8)
    at Object.<anonymous> (/Users/sinchang/Desktop/node-notes/lib/mongo.js:7:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sinchang/Desktop/node-notes/models/users.js:5:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
My Noteslistening on port3000
(node:60061) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: invalid schema, expected mongodb
(node:60061) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:60061) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
Unhandled rejection Error
    at Model.ensureIndex (/Users/sinchang/Desktop/node-notes/node_modules/.2.3.2@mongolass/lib/query.js:107:16)
    at Object.<anonymous> (/Users/sinchang/Desktop/node-notes/lib/mongo.js:17:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sinchang/Desktop/node-notes/models/users.js:5:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)

Error
    at Model.insert (/Users/sinchang/Desktop/node-notes/node_modules/.2.3.2@mongolass/lib/query.js:107:16)
    at Object.create (/Users/sinchang/Desktop/node-notes/models/users.js:9:21)
    at /Users/sinchang/Desktop/node-notes/routes/signup.js:62:15
    at Layer.handle [as handle_request] (/Users/sinchang/Desktop/node-notes/node_modules/.4.14.0@express/lib/router/layer.js:95:5)
    at next (/Users/sinchang/Desktop/node-notes/node_modules/.4.14.0@express/lib/router/route.js:131:13)
    at checkNotLogin (/Users/sinchang/Desktop/node-notes/middlewares/check.js:15:3)
    at Layer.handle [as handle_request] (/Users/sinchang/Desktop/node-notes/node_modules/.4.14.0@express/lib/router/layer.js:95:5)
    at next (/Users/sinchang/Desktop/node-notes/node_modules/.4.14.0@express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/sinchang/Desktop/node-notes/node_modules/.4.14.0@express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/sinchang/Desktop/node-notes/node_modules/.4.14.0@express/lib/router/layer.js:95:5)
    at /Users/sinchang/Desktop/node-notes/node_modules/.4.14.0@express/lib/router/index.js:277:22
    at Function.process_params (/Users/sinchang/Desktop/node-notes/node_modules/.4.14.0@express/lib/router/index.js:330:12)
    at next (/Users/sinchang/Desktop/node-notes/node_modules/.4.14.0@express/lib/router/index.js:271:10)
    at Function.handle (/Users/sinchang/Desktop/node-notes/node_modules/.4.14.0@express/lib/router/index.js:176:3)
    at router (/Users/sinchang/Desktop/node-notes/node_modules/.4.14.0@express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/Users/sinchang/Desktop/node-notes/node_modules/.4.14.0@express/lib/router/layer.js:95:5)
```

环境版本：
- mogodb:3.0.7 
- node:7.2.0 
- express:4.14.0

请问如何解决？

**Comment by nswbmw** [comment]
你是不是 mongodb 的配置不是以  `mongodb://` 开头的...
