### ISSUE TITLE
mongolass 使用了es6的语法没有加babel编译

### ISSUE THREAD

**Issue by zsg857981535** [nswbmw/N-blog#241]
D:\nodejs\myblog\node_modules\mongolass\lib\query.js:53
        this[plugin.name] = (...args) => {
                             ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\nodejs\myblog\node_modules\mongolass\lib\model.js:
7:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by nswbmw** [comment]
see https://github.com/nswbmw/N-blog/issues/240
