### ISSUE TITLE
部署到heroku出现的问题

### ISSUE THREAD

**Issue by Lueny-cn** [nswbmw/N-blog#251]
打印 heroku logs显示以下信息:
2016-12-11T05:27:22.017745+00:00 heroku[slug-compiler]: Slug compilation started
2016-12-11T05:27:22.017751+00:00 heroku[slug-compiler]: Slug compilation finished
2016-12-11T05:27:22.026688+00:00 heroku[web.1]: State changed from crashed to starting
2016-12-11T05:27:24.719797+00:00 heroku[web.1]: Starting process with command `npm start`
2016-12-11T05:27:28.621761+00:00 app[web.1]: > mybloglueny@1.0.0 start /app
2016-12-11T05:27:28.621762+00:00 app[web.1]: > NODE_ENV=production pm2 start index.js --node-args='--harmony' --name 'mybloglueny'
2016-12-11T05:27:28.621763+00:00 app[web.1]:
2016-12-11T05:27:28.621738+00:00 app[web.1]:
2016-12-11T05:27:29.242885+00:00 app[web.1]:
2016-12-11T05:27:29.242898+00:00 app[web.1]:                         -------------
2016-12-11T05:27:29.242899+00:00 app[web.1]:
2016-12-11T05:27:29.242900+00:00 app[web.1]:    Looking for a complete monitoring and management tool for PM2?
2016-12-11T05:27:29.242901+00:00 app[web.1]:     _                             _        _            _
2016-12-11T05:27:29.242901+00:00 app[web.1]:    | | _____ _   _ _ __ ___   ___| |_ _ __(_) ___ ___  (_) ___
2016-12-11T05:27:29.242902+00:00 app[web.1]:    | |/ / _ \ | | | '_ ` _ \ / _ \ __| '__| |/ __/ __| | |/ _ \
2016-12-11T05:27:29.242903+00:00 app[web.1]:    |   <  __/ |_| | | | | | |  __/ |_| |  | | (__\__ \_| | (_) |
2016-12-11T05:27:29.242903+00:00 app[web.1]:    |_|\_\___|\__, |_| |_| |_|\___|\__|_|  |_|\___|___(_)_|\___/
2016-12-11T05:27:29.242904+00:00 app[web.1]:              |___/
2016-12-11T05:27:29.242906+00:00 app[web.1]:                           Features
2016-12-11T05:27:29.242905+00:00 app[web.1]:
2016-12-11T05:27:29.242906+00:00 app[web.1]:
2016-12-11T05:27:29.242907+00:00 app[web.1]:                    - Real Time Dashboard
2016-12-11T05:27:29.242908+00:00 app[web.1]:                    - CPU/Memory monitoring
2016-12-11T05:27:29.242908+00:00 app[web.1]:                    - HTTP monitoring
2016-12-11T05:27:29.242909+00:00 app[web.1]:                    - Event notification
2016-12-11T05:27:29.242909+00:00 app[web.1]:                    - Custom value monitoring
2016-12-11T05:27:29.242910+00:00 app[web.1]:                    - Real Time log display
2016-12-11T05:27:29.242910+00:00 app[web.1]:
2016-12-11T05:27:29.242911+00:00 app[web.1]:                           Checkout
2016-12-11T05:27:29.242911+00:00 app[web.1]:
2016-12-11T05:27:29.242912+00:00 app[web.1]:                    https://keymetrics.io/
2016-12-11T05:27:29.242913+00:00 app[web.1]:
2016-12-11T05:27:29.242913+00:00 app[web.1]:                         -------------
2016-12-11T05:27:29.242914+00:00 app[web.1]:
2016-12-11T05:27:29.377727+00:00 app[web.1]: [PM2] Spawning PM2 daemon with pm2_home=/app/.pm2
2016-12-11T05:27:30.268299+00:00 app[web.1]: [PM2] PM2 Successfully daemonized
2016-12-11T05:27:30.446639+00:00 app[web.1]: [PM2] Starting /app/index.js in fork_mode (1 instance)
2016-12-11T05:27:30.545729+00:00 app[web.1]: [PM2] Done.
2016-12-11T05:27:30.685485+00:00 app[web.1]: ┌─────────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬───────────┬──────────┐
2016-12-11T05:27:30.685489+00:00 app[web.1]: │ App name    │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem       │ watching │
2016-12-11T05:27:30.685490+00:00 app[web.1]: ├─────────────┼────┼──────┼─────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
2016-12-11T05:27:30.685490+00:00 app[web.1]: │ mybloglueny │ 0  │ fork │ 33  │ online │ 0       │ 0s     │ 7%  │ 13.2 MB   │ disabled │
2016-12-11T05:27:30.685491+00:00 app[web.1]: └─────────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴───────────┴──────────┘
2016-12-11T05:27:30.685566+00:00 app[web.1]:  Use `pm2 show <id|name>` to get more details about an app
2016-12-11T05:27:30.849491+00:00 heroku[web.1]: State changed from starting to crashed
2016-12-11T05:27:30.831182+00:00 heroku[web.1]: Process exited with status 0

然后再打开 https://bloglueny.herokuapp.com/  不能正确显示, 感觉是用pm2启动成功了, 远程数据库在本地也连接成功了, 不知道在是什么问题, 请指教

**Comment by Lueny-cn** [comment]
![image](https://cloud.githubusercontent.com/assets/15892982/21078473/d354d4fa-bfab-11e6-8511-7e709e833dcb.png)
在stackoverflow  找了这个问题后, 修改了端口号也是不行, 还是是出现这个问题

**Comment by nswbmw** [comment]
看看是不是 https://github.com/nswbmw/N-blog/commit/d86d3d5f609f15eb332dee8906783bb5927ea88f

**Comment by Lueny-cn** [comment]
![image](https://cloud.githubusercontent.com/assets/15892982/21080963/37f9cd3e-bff7-11e6-8ec2-58c8f53f1736.png)
已经排除过了, 然后我把之前的仓库删掉再重新push也是不行, 有点奇怪

**Comment by ElvisVern** [comment]
0|myblog   |     at tryOnTimeout (timers.js:224:11)
0|myblog   |     at Timer.listOnTimeout (timers.js:198:5)
0|myblog   | Sat, 10 Dec 2016 19:31:38 GMT express-session deprecated undefined resave option; provide resave option at index.js:25:9
0|myblog   | Sat, 10 Dec 2016 19:31:38 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at index.js:25:9
0|myblog   | (node:1934) Warning: Possible EventEmitter memory leak detected. 11 field listeners added. Use emitter.setMaxListeners() to increase limit
0|myblog   | (node:1934) Warning: Possible EventEmitter memory leak detected. 11 file listeners added. Use emitter.setMaxListeners() to increase limit
0|myblog   | (node:1934) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
0|myblog   | (node:1934) Warning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit
0|myblog   | Mon, 12 Dec 2016 17:48:09 GMT express-session deprecated undefined resave option; provide resave option at index.js:25:9
0|myblog   | Mon, 12 Dec 2016 17:48:09 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at index.js:25:9


我是这个问题..  不是很懂 = =

**Comment by ThatToti** [comment]
## heroku部署问题解决

### application error：

> 项目中缺失一份Procfile文件||端口设置错误

但博主的教程中，端口是没有问题的

### 具体解法如下

1. 在根项目中添加一份Procfile文件，文件直接命名为Procfile
2. 文件里，`web: node index.js` 一行即可。`index.js`为你的执行文件名，有些人也用`app.js`
3. 然后git commit&push
4. pm2 `npm restart`

这个问题就应该解决了

**Comment by nswbmw** [comment]
@ThatToti 貌似是有 Procfile 这么一回事，好久不搞 Heroku 都忘了。。欢迎 pr

**Comment by Lueny-cn** [comment]
@ThatToti  已经解决啦. thanks~
