### ISSUE TITLE
update文章的时候报错，问题定位不到

### ISSUE THREAD

**Issue by Flashylone** [nswbmw/N-blog#252]

**Comment by Flashylone** [comment]
Error
   at Model.update (/Users/yuman/Documents/Node/myblog/node_modules/.npminstall/mongolass/2.3.2/mongolass/lib/query.js:107:16)
   at Object.module.exports.updatePostById (/Users/yuman/Documents/Node/myblog/models/posts.js:67:15)
   at /Users/yuman/Documents/Node/myblog/routes/posts.js:109:13
   at Layer.handle [as handle_request] (/Users/yuman/Documents/Node/myblog/node_modules/.npminstall/express/4.14.0/express/lib/router/layer.js:95:5)
   at next (/Users/yuman/Documents/Node/myblog/node_modules/.npminstall/express/4.14.0/express/lib/router/route.js:131:13)
   at module.exports.checkLogin (/Users/yuman/Documents/Node/myblog/middlewares/check.js:11:3)
   at Layer.handle [as handle_request] (/Users/yuman/Documents/Node/myblog/node_modules/.npminstall/express/4.14.0/express/lib/router/layer.js:95:5)
   at next (/Users/yuman/Documents/Node/myblog/node_modules/.npminstall/express/4.14.0/express/lib/router/route.js:131:13)
   at Route.dispatch (/Users/yuman/Documents/Node/myblog/node_modules/.npminstall/express/4.14.0/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/Users/yuman/Documents/Node/myblog/node_modules/.npminstall/express/4.14.0/express/lib/router/layer.js:95:5)
   at /Users/yuman/Documents/Node/myblog/node_modules/.npminstall/express/4.14.0/express/lib/router/index.js:277:22
   at param (/Users/yuman/Documents/Node/myblog/node_modules/.npminstall/express/4.14.0/express/lib/router/index.js:349:14)
   at param (/Users/yuman/Documents/Node/myblog/node_modules/.npminstall/express/4.14.0/express/lib/router/index.js:365:14)
   at Function.process_params (/Users/yuman/Documents/Node/myblog/node_modules/.npminstall/express/4.14.0/express/lib/router/index.js:410:3)
   at next (/Users/yuman/Documents/Node/myblog/node_modules/.npminstall/express/4.14.0/express/lib/router/index.js:271:10)
   at Function.handle (/Users/yuman/Documents/Node/myblog/node_modules/.npminstall/express/4.14.0/express/lib/router/index.js:176:3)
