### ISSUE TITLE
跟着学到权限控制一直报错

### ISSUE THREAD

**Issue by Lojze** [nswbmw/N-blog#253]
E:\node-index\mybold\index.js:23
    name: config.session.key,
                        ^

TypeError: Cannot read property 'key' of undefined
    at Object.<anonymous> (E:\node-index\mybold\index.js:23:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

![image](https://cloud.githubusercontent.com/assets/11644830/21092110/7a053f40-c085-11e6-85de-0334844b9d8c.png)
请教一下：MongoDB配置错了吗，代码都是跟着写的，望抽空看一下

**Comment by Lojze** [comment]
文件名称搞错了，config写成了congif-。-，还是感谢
