### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by misshy** [nswbmw/N-blog#256]
```
λ node index.js
D:\下载\N-blog-master\N-blog-master\node_modules\mongolass\lib\query.js:53
        this[plugin.name] = (...args) => {
                             ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\下载\N-blog-master\N-blog-master\node_modules\mongolass\lib\model.js:7:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\下载\N-blog-master\N-blog-master\node_modules\mongolass\lib\index.js:7:15)
    at Module._compile (module.js:409:26)

```
请问这是什么错误引起的啊

**Comment by nswbmw** [comment]
用 node@6 +

**Comment by misshy** [comment]
解决了 谢谢大神
