### ISSUE TITLE
您好,博主,发表文章不成功

### ISSUE THREAD

**Issue by GuoJieLun** [nswbmw/N-blog#269]
我按照您的文章去写这个博客,然后到了发表文章这里就一直提示错类型不对
`Error: ($.author: "586f51c0bd96e52314b5aa38") ✖ (type: ObjectId)
   at throwError (C:\Users\Administrator\Desktop\myProject\blog\j-blog\node_modules\mongolass\node_modules\another-json-schema\index.js:213:17)
   at validate (C:\Users\Administrator\Desktop\myProject\blog\j-blog\node_modules\mongolass\node_modules\another-json-schema\index.js:184:7)
   at validateLeaf (C:\Users\Administrator\Desktop\myProject\blog\j-blog\node_modules\mongolass\node_modules\another-json-schema\index.js:175:12)
   at iterator (C:\Users\Administrator\Desktop\myProject\blog\j-blog\node_modules\mongolass\node_modules\another-json-schema\index.js:120:14)
   at iterator (C:\Users\Administrator\Desktop\myProject\blog\j-blog\node_modules\mongolass\node_modules\another-json-schema\index.js:133:29)
   at _validateObject (C:\Users\Administrator\Desktop\myProject\blog\j-blog\node_modules\mongolass\node_modules\another-json-schema\index.js:108:11)
   at _Schema.validate (C:\Users\Administrator\Desktop\myProject\blog\j-blog\node_modules\mongolass\node_modules\another-json-schema\index.js:38:10)
   at formatCreate (C:\Users\Administrator\Desktop\myProject\blog\j-blog\node_modules\mongolass\lib\schema.js:183:25)
   at C:\Users\Administrator\Desktop\myProject\blog\j-blog\node_modules\mongolass\lib\schema.js:90:27
   at Array.forEach (native)
   at Query.beforeInsert (C:\Users\Administrator\Desktop\myProject\blog\j-blog\node_modules\mongolass\lib\schema.js:90:12)
   at C:\Users\Administrator\Desktop\myProject\blog\j-blog\node_modules\mongolass\lib\query.js:146:44
   at next (native)
   at onFulfilled (C:\Users\Administrator\Desktop\myProject\blog\j-blog\node_modules\mongolass\node_modules\co\index.js:65:19)
   at C:\Users\Administrator\Desktop\myProject\blog\j-blog\node_modules\mongolass\node_modules\co\index.js:54:5
   at co (C:\Users\Administrator\Desktop\myProject\blog\j-blog\node_modules\mongolass\node_modules\co\index.js:50:10)
   at Query.execBeforePlugins (C:\Users\Administrator\Desktop\myProject\blog\j-blog\node_modules\mongolass\lib\query.js:142:10)
   at C:\Users\Administrator\Desktop\myProject\blog\j-blog\node_modules\mongolass\lib\query.js:67:39
   at tryCatcher (C:\Users\Administrator\Desktop\myProject\blog\j-blog\node_modules\mongolass\node_modules\bluebird\js\release\util.js:16:23)
   at Promise._settlePromiseFromHandler (C:\Users\Administrator\Desktop\myProject\blog\j-blog\node_modules\mongolass\node_modules\bluebird\js\release\promise.js:510:31)
   at Promise._settlePromise (C:\Users\Administrator\Desktop\myProject\blog\j-blog\node_modules\mongolass\node_modules\bluebird\js\release\promise.js:567:18)
   at Promise._settlePromiseCtx (C:\Users\Administrator\Desktop\myProject\blog\j-blog\node_modules\mongolass\node_modules\bluebird\js\release\promise.js:604:10`

希望能技术支持一下,打扰了,谢谢.

**Comment by nswbmw** [comment]
把你代码提交到 GitHub 我看下吧

**Comment by GuoJieLun** [comment]
这一段是post
--------------------------------------
`
    var author = req.session.user._id;
    var title = req.fields.title;
    var content = req.fields.content;

    // 校验参数
    try {
        if (!title.length) {
            throw new Error('请填写标题');
        }
        if (!content.length) {
            throw new Error('请填写内容');
        }
    } catch (e) {
        req.flash('error', e.message);
        return res.redirect('back');
    }

    var post = {
        author: author,
        title: title,
        content: content,
        pv: 0
    };

    PostModel.create(post)
        .then(function (result) {
            // 此 post 是插入 mongodb 后的值，包含 _id
            post = result.ops[0];
            req.flash('success', '发表成功');
            // 发表成功后跳转到该文章页
            res.redirect('/posts/${post._id}');
        })
        .catch(next);
`
--------------------------------------

`//创建文章
exports.Post = mongolass.model('Post', { 

    author: { type: Mongolass.Types.ObjectId },

    title: { type: 'string' },

    content: { type: 'string' },

    pv: { type: 'number' }
});`

**Comment by nswbmw** [comment]
这样看是没有问题的，我之前的意思是你把整个项目提交到你的 GitHub 我看下。

**Comment by GuoJieLun** [comment]
好的,稍等一下

**Comment by GuoJieLun** [comment]
@nswbmw https://github.com/GuoJieLun/study/tree/master/j-blog 好了

**Comment by nswbmw** [comment]
```
res.redirect('/posts/${post._id}')
```

改成：

```
res.redirect(`/posts/${post._id}`)
```

**Comment by GuoJieLun** [comment]
还是不行,打扰了博主,我先下载你的源码启动看看整个流程,应该是我敲代码哪里敲错了.3Q,博主的的快速回答

**Comment by yikeguo** [comment]
同类情况   把author: { type: Mongolass.Types.ObjectId }  中改下 type:'string' 可以上传 ，但后面查看文章又有问题

**Comment by AmazingZhao** [comment]
博主可以加个微信吗？只为在微信上能得到你及时的回复。膜拜~
