### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by Jupiter-Lee** [nswbmw/N-blog#287]
运行完node index.js 报错如下，提示的是模块代码里面的语法错误，然后我就困惑了...，我GitHub里面有出错的源码
E:\test\myblog>node index.js
express-session deprecated undefined resave option; provide resave option index.
js:20:9
express-session deprecated undefined saveUninitialized option; provide saveUnini
tialized option index.js:20:9
E:\test\myblog\node_modules\mongolass\lib\query.js:54
        this[plugin.name] = (...args) => {
                             ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\test\myblog\node_modules\mongolass\lib\model.js:7:
15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\test\myblog\node_modules\mongolass\lib\index.js:7:
15)
    at Module._compile (module.js:409:26)

**Comment by nswbmw** [comment]
用 node@4+，加 `haromny`
