### ISSUE TITLE
遇到报错：TypeError: Post.find(...).populate(...).sort(...).addCreatedAt is not a function

### ISSUE THREAD

**Issue by chaohangz** [nswbmw/N-blog#292]
下面是完整的错误信息：
TypeError: Post.find(...).populate(...).sort(...).addCreatedAt is not a function
   at Object.getPosts (/Users/chaohangz/myblog/models/posts.js:46:8)
   at /Users/chaohangz/myblog/routes/posts.js:12:13
   at Layer.handle [as handle_request] (/Users/chaohangz/myblog/node_modules/.4.14.1@express/lib/router/layer.js:95:5)
   at next (/Users/chaohangz/myblog/node_modules/.4.14.1@express/lib/router/route.js:131:13)
   at Route.dispatch (/Users/chaohangz/myblog/node_modules/.4.14.1@express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/Users/chaohangz/myblog/node_modules/.4.14.1@express/lib/router/layer.js:95:5)
   at /Users/chaohangz/myblog/node_modules/.4.14.1@express/lib/router/index.js:277:22
   at Function.process_params (/Users/chaohangz/myblog/node_modules/.4.14.1@express/lib/router/index.js:330:12)
   at next (/Users/chaohangz/myblog/node_modules/.4.14.1@express/lib/router/index.js:271:10)
   at Function.handle (/Users/chaohangz/myblog/node_modules/.4.14.1@express/lib/router/index.js:176:3)
   at router (/Users/chaohangz/myblog/node_modules/.4.14.1@express/lib/router/index.js:46:12)
   at Layer.handle [as handle_request] (/Users/chaohangz/myblog/node_modules/.4.14.1@express/lib/router/layer.js:95:5)
   at trim_prefix (/Users/chaohangz/myblog/node_modules/.4.14.1@express/lib/router/index.js:312:13)
   at /Users/chaohangz/myblog/node_modules/.4.14.1@express/lib/router/index.js:280:7
   at Function.process_params (/Users/chaohangz/myblog/node_modules/.4.14.1@express/lib/router/index.js:330:12)
   at next (/Users/chaohangz/myblog/node_modules/.4.14.1@express/lib/router/index.js:271:10)
   at /Users/chaohangz/myblog/index.js:52:3
   at Layer.handle [as handle_request] (/Users/chaohangz/myblog/node_modules/.4.14.1@express/lib/router/layer.js:95:5)
   at trim_prefix (/Users/chaohangz/myblog/node_modules/.4.14.1@express/lib/router/index.js:312:13)
   at /Users/chaohangz/myblog/node_modules/.4.14.1@express/lib/router/index.js:280:7
   at Function.process_params (/Users/chaohangz/myblog/node_modules/.4.14.1@express/lib/router/index.js:330:12)
   at next (/Users/chaohangz/myblog/node_modules/.4.14.1@express/lib/router/index.js:271:10)

myblog/modules/posts.js 中的部分代码 36行至49行

```javaScript
// 按创建时间降序获取所有用户文章或者某个特定用户的所有文章
  getPosts: function getPosts(author) {
    var query = {}
    if (author) {
      query.author = author
    }
    return Post
      .find(query)
      .populate({path: 'author', model: 'User'})
      .sort({_id: -1})
      .addCreatedAt()    // 错误信息中显示的第46行是 
      .contentToHtml()
      .exec()
  },
```

myblog/routes/posts.js 中的调用

```javascript
// GET /posts 所有用户或者特定用户的文章页
router.get('/', function(req, res, next) {
  var author = req.query.author

  PostModel.getPosts(author)     // 错误信息所显示的第12行
    .then(function (posts) {
      res.render('posts', {
        posts: posts
      })
    })
    .catch(next)
})
```

**Comment by chaohangz** [comment]
我自己 addCreatedAt 写错了

**Comment by woyigmwwwhw** [comment]
这个怎么做啊，我也遇到了这样的问题@chaohangz
