### ISSUE TITLE
用koa-generator 改写该项目

### ISSUE THREAD

**Issue by Zaynex** [nswbmw/N-blog#295]
在路由设计这一部分，middlewares 总是
```
`middleware` must be a function, not `object`
    at Layer.<anonymous> (E:\koa-blog\node_modules\.5.4.0@koa-router\lib\layer.js:38:13)
    at Array.forEach (native)
    at new Layer (E:\koa-blog\node_modules\.5.4.0@koa-router\lib\layer.js:35:14)
    at Router.register (E:\koa-blog\node_modules\.5.4.0@koa-router\lib\router.js:508:15)
    at Router.use (E:\koa-blog\node_modules\.5.4.0@koa-router\lib\router.js:257:12)
```
麻烦看一下
https://github.com/Zaynex/koa-blog
蟹蟹！

**Comment by nswbmw** [comment]
```
module.exports = router;
```
改成：
```
module.exports = router.routes();
```

**Comment by Zaynex** [comment]
现在遇到的问题是 500报错， 路由应该都配置正确了，麻烦再看看，希望这个repo能够成为你的koa版本 @nswbmw

**Comment by nswbmw** [comment]
我看了，你是没弄明白 koa-router 的用法啊。。先去看看文档吧
