### ISSUE TITLE
博主大大，我写到routes/posts.js 后运行后报segmentation fault  node index.js错误

### ISSUE THREAD

**Issue by HiLanner** [nswbmw/N-blog#303]
你好，
   我写到查看所有文章列表的地方开始报错，感觉是数据库查询数据的时候出现了问题，代码基本都是按照你写的那样写的，今天查了一天，还是没发现哪里有错，只能求救你了，拜托拜托
   git地址是 https://github.com/HiLanner/blog-node-mongoldb.git

**Comment by nswbmw** [comment]
我试了下没有遇到报错，你把报错信息贴下

**Comment by HiLanner** [comment]
只要一访问http://localhost:3000/posts就是报这个错误

[1]    3986 segmentation fault  node index.js

简直让我无从下手

另外我的node版本是7.4.0
mongodb版本是3.4.2
express版本是4.14.1

**Comment by HiLanner** [comment]
当报栈错误之后
我登录再进入   http://localhost:3000/posts  的时候
又会报
TypeError: Cannot read property 'replace' of undefined
Please report this to https://github.com/chjj/marked.
   at Lexer.lex (/Users/chengshenglan/study/myblog/node_modules/marked/lib/marked.js:138:5)
   at Function.Lexer.lex (/Users/chengshenglan/study/myblog/node_modules/marked/lib/marked.js:129:16)
   at marked (/Users/chengshenglan/study/myblog/node_modules/marked/lib/marked.js:1219:31)
   at /Users/chengshenglan/study/myblog/models/posts.js:9:28
   at Array.map (native)
   at Query.afterFind (/Users/chengshenglan/study/myblog/models/posts.js:8:22)
   at /Users/chengshenglan/study/myblog/node_modules/mongolass/lib/query.js:173:44
   at Generator.next (<anonymous>)
   at onFulfilled (/Users/chengshenglan/study/myblog/node_modules/co/index.js:65:19)
   at tryCatcher (/Users/chengshenglan/study/myblog/node_modules/mongolass/node_modules/bluebird/js/release/util.js:16:23)
   at Promise._settlePromiseFromHandler (/Users/chengshenglan/study/myblog/node_modules/mongolass/node_modules/bluebird/js/release/promise.js:510:31)
   at Promise._settlePromise (/Users/chengshenglan/study/myblog/node_modules/mongolass/node_modules/bluebird/js/release/promise.js:567:18)
   at Promise._settlePromiseCtx (/Users/chengshenglan/study/myblog/node_modules/mongolass/node_modules/bluebird/js/release/promise.js:604:10)
   at Async._drainQueue (/Users/chengshenglan/study/myblog/node_modules/mongolass/node_modules/bluebird/js/release/async.js:143:12)
   at Async._drainQueues (/Users/chengshenglan/study/myblog/node_modules/mongolass/node_modules/bluebird/js/release/async.js:148:10)
   at Immediate.Async.drainQueues (/Users/chengshenglan/study/myblog/node_modules/mongolass/node_modules/bluebird/js/release/async.js:17:14)
   at runCallback (timers.js:651:20)
   at tryOnImmediate (timers.js:624:5)
   at processImmediate [as _immediateCallback] (timers.js:596:5)
----- Mongolass error stack -----
Error
   at Model.find (/Users/chengshenglan/study/myblog/node_modules/mongolass/lib/query.js:108:16)
   at Object.getPosts (/Users/chengshenglan/study/myblog/models/posts.js:43:14)
   at /Users/chengshenglan/study/myblog/routes/posts.js:12:15
   at Layer.handle [as handle_request] (/Users/chengshenglan/study/myblog/node_modules/express/lib/router/layer.js:95:5)
   at next (/Users/chengshenglan/study/myblog/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/Users/chengshenglan/study/myblog/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/Users/chengshenglan/study/myblog/node_modules/express/lib/router/layer.js:95:5)
   at /Users/chengshenglan/study/myblog/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/Users/chengshenglan/study/myblog/node_modules/express/lib/router/index.js:330:12)
   at next (/Users/chengshenglan/study/myblog/node_modules/express/lib/router/index.js:271:10)
   at Function.handle (/Users/chengshenglan/study/myblog/node_modules/express/lib/router/index.js:176:3)
   at router (/Users/chengshenglan/study/myblog/node_modules/express/lib/router/index.js:46:12)
   at Layer.handle [as handle_request] (/Users/chengshenglan/study/myblog/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/Users/chengshenglan/study/myblog/node_modules/express/lib/router/index.js:312:13)
   at /Users/chengshenglan/study/myblog/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/Users/chengshenglan/study/myblog/node_modules/express/lib/router/index.js:330:12)
   at next (/Users/chengshenglan/study/myblog/node_modules/express/lib/router/index.js:271:10)
   at /Users/chengshenglan/study/myblog/index.js:49:5
   at Layer.handle [as handle_request] (/Users/chengshenglan/study/myblog/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/Users/chengshenglan/study/myblog/node_modules/express/lib/router/index.js:312:13)
   at /Users/chengshenglan/study/myblog/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/Users/chengshenglan/study/myblog/node_modules/express/lib/router/index.js:330:12)


原谅我这个不能发图～～～
