### ISSUE TITLE
無法連接 mongodb

### ISSUE THREAD

**Issue by alanaudi** [nswbmw/N-blog#310]
我照著版主的教學做到 #4.4  執行 supervisor --harmony index 後，得到了錯誤訊息如下:
Unhandled rejection MongoError: not authorized on alanaudi to execute command { list Indexes: "sessions",cursor: {} }
    at Function.MongoError.create (/home/alanaudi/myblog/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/home/alanaudi/myblog/node_modules/mongodb-core/lib/cursor.js:212:36)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
在伺服器上我沒有 sudo 權限，但有 自己的 mongodb 帳號，這個問題似乎是要我在 config/default.js 進行認證，請問我該如何使用 mongodb

**Comment by nswbmw** [comment]
加上用户名密码连 mongodb
