### ISSUE TITLE
问题：数据库插入数据异常

### ISSUE THREAD

**Issue by oceanhaiyang** [nswbmw/N-blog#313]
当执行本行时var UserModel = require('../models/users');
报错
D:\myblog\node_modules\mongolass\lib\query.js:54
        this[plugin.name] = (...args) => {
                             ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
是mongo版本与node不兼容吗？

**Comment by oceanhaiyang** [comment]
node版本是4+

**Comment by nswbmw** [comment]
@oceanhaiyang node@4 开 `--harmony` 试试

**Comment by oceanhaiyang** [comment]
好的，为什么用node index不行呢

**Comment by nswbmw** [comment]
http://node.green/
