### ISSUE TITLE
发布文章成功之后，访问主页出现：TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by OneTwoSmall** [nswbmw/N-blog#318]
1.错误信息如下：
TypeError: Cannot read property 'map' of undefined
   at Query.afterFind (D:\GitWorkSpace\StudyNodeClub\models\posts.js:10:21)
   at D:\GitWorkSpace\StudyNodeClub\node_modules\mongolass\lib\query.js:173:44
   at next (native)
   at onFulfilled (D:\GitWorkSpace\StudyNodeClub\node_modules\co\index.js:65:19)
   at tryCatcher (D:\GitWorkSpace\StudyNodeClub\node_modules\mongolass\node_modules\bluebird\js\release\util.js:16:23)
   at Promise._settlePromiseFromHandler (D:\GitWorkSpace\StudyNodeClub\node_modules\mongolass\node_modules\bluebird\js\release\promise.js:510:31)
   at Promise._settlePromise (D:\GitWorkSpace\StudyNodeClub\node_modules\mongolass\node_modules\bluebird\js\release\promise.js:567:18)
   at Promise._settlePromiseCtx (D:\GitWorkSpace\StudyNodeClub\node_modules\mongolass\node_modules\bluebird\js\release\promise.js:604:10)
   at Async._drainQueue (D:\GitWorkSpace\StudyNodeClub\node_modules\mongolass\node_modules\bluebird\js\release\async.js:143:12)
   at Async._drainQueues (D:\GitWorkSpace\StudyNodeClub\node_modules\mongolass\node_modules\bluebird\js\release\async.js:148:10)
   at Immediate.Async.drainQueues (D:\GitWorkSpace\StudyNodeClub\node_modules\mongolass\node_modules\bluebird\js\release\async.js:17:14)
   at runCallback (timers.js:649:20)
   at tryOnImmediate (timers.js:622:5)
   at processImmediate [as _immediateCallback] (timers.js:594:5) 
----- Mongolass error stack ----- 
Error
   at Model.find (D:\GitWorkSpace\StudyNodeClub\node_modules\mongolass\lib\query.js:108:16)
   at Object.getPosts (D:\GitWorkSpace\StudyNodeClub\models\posts.js:44:14)
   at D:\GitWorkSpace\StudyNodeClub\routes\posts.js:14:15
   at Layer.handle [as handle_request] (D:\GitWorkSpace\StudyNodeClub\node_modules\express\lib\router\layer.js:95:5)
   at next (D:\GitWorkSpace\StudyNodeClub\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (D:\GitWorkSpace\StudyNodeClub\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (D:\GitWorkSpace\StudyNodeClub\node_modules\express\lib\router\layer.js:95:5)
   at D:\GitWorkSpace\StudyNodeClub\node_modules\express\lib\router\index.js:277:22
   at Function.process_params (D:\GitWorkSpace\StudyNodeClub\node_modules\express\lib\router\index.js:330:12)
   at next (D:\GitWorkSpace\StudyNodeClub\node_modules\express\lib\router\index.js:271:10)
   at Function.handle (D:\GitWorkSpace\StudyNodeClub\node_modules\express\lib\router\index.js:176:3)
   at router (D:\GitWorkSpace\StudyNodeClub\node_modules\express\lib\router\index.js:46:12)
   at Layer.handle [as handle_request] (D:\GitWorkSpace\StudyNodeClub\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (D:\GitWorkSpace\StudyNodeClub\node_modules\express\lib\router\index.js:312:13)
   at D:\GitWorkSpace\StudyNodeClub\node_modules\express\lib\router\index.js:280:7
   at Function.process_params (D:\GitWorkSpace\StudyNodeClub\node_modules\express\lib\router\index.js:330:12)
   at next (D:\GitWorkSpace\StudyNodeClub\node_modules\express\lib\router\index.js:271:10)
   at D:\GitWorkSpace\StudyNodeClub\index.js:54:5
   at Layer.handle [as handle_request] (D:\GitWorkSpace\StudyNodeClub\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (D:\GitWorkSpace\StudyNodeClub\node_modules\express\lib\router\index.js:312:13)
   at D:\GitWorkSpace\StudyNodeClub\node_modules\express\lib\router\index.js:280:7
   at Function.process_params (D:\GitWorkSpace\StudyNodeClub\node_modules\express\lib\router\index.js:330:12)
2.根据错误信息和调试发现在调用
     PostModel.getPosts(author)
        .then(function (posts) {
            res.render('posts', {
                posts: posts
            });
        }).catch(next);
这个getPosts方法时没有找到数据。
然而不知道为什么查询不到，请博主帮忙看一下，谢谢
我上传的这里了：[StudyNode](https://github.com/OneTwoSmall/StudyNodeClub)

**Comment by OneTwoSmall** [comment]
通过对比正确的代码， 发现在mongo.js中的addCreatedAt插件绑定的第一个afterFind方法中没有return结果。。。加上之后OK了。
QAQ
