### ISSUE TITLE
路由设置问题...

### ISSUE THREAD

**Issue by zhuohangzhao** [nswbmw/N-blog#340]
/Users/hank/code/my-code/myblog/node_modules/express/lib/router/route.js:202
        throw new Error(msg);
        ^

Error: Route.get() requires callback functions but got a [object Undefined]
    at Route.(anonymous function) [as get] (/Users/hank/code/my-code/myblog/node_modules/express/lib/router/route.js:202:15)
    at Function.proto.(anonymous function) [as get] (/Users/hank/code/my-code/myblog/node_modules/express/lib/router/index.js:510:19)
    at Object.<anonymous> (/Users/hank/code/my-code/myblog/routes/signout.js:7:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/hank/code/my-code/myblog/routes/index.js:7:23)
    at Object.<anonymous> (/Users/hank/code/my-code/myblog/index.js:86:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

**Comment by zhuohangzhao** [comment]
是checkLogin 和 checkNotLogin 引入问题
