### ISSUE TITLE
config-lite失效了

### ISSUE THREAD

**Issue by yjhmelody** [nswbmw/N-blog#354]
原来可以用的，现在用不了，只能把配置文件耦合在index.js里了
TypeError: Cannot read property 'maxAge' of undefined

代码基本跟教程一致的，就这里不行。求教！！不知道什么原因

**Comment by hizoubin** [comment]
是4.4这部分吗?我也遇到了这个问题。
报错信息：
```
/Users/web/Desktop/light/index.js:22
  name: config.session.key,// 设置 cookie 中保存 session id 的字段名称
                                     ^

TypeError: Cannot read property 'key' of undefined
    at Object.<anonymous> (/Users/web/Desktop/light/index.js:22:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
```

**Comment by nswbmw** [comment]
看看 config-lite 版本

**Comment by yjhmelody** [comment]
"config-lite": "^2.0.0"

**Comment by freebreaker** [comment]
同问，session里的key显示未定义

**Comment by qiuncheng** [comment]
使用这种方式可以var config = require('config-lite')(__dirname);
