### ISSUE TITLE
express-session出现问题

### ISSUE THREAD

**Issue by LeoCecilia** [nswbmw/N-blog#363]
F:\nBlog\node_modules\express-session\index.js:171
  store.on('disconnect', function ondisconnect() {
        ^

TypeError: store.on is not a function
    at session (F:\nBlog\node_modules\express-session\index.js:171:9)
    at Object.<anonymous> (F:\nBlog\index.js:21:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

感觉说的是设置session的store属性的时候，不能以函数的形式进行调用
``` javascript
var session = require('express-session');
var MongoStore = require('connect-flash');
app.use(session({
  name: config.session.key,//设置cookie中保存sessionid
  secret: config.session.secret,
// 通过设置 secret 来计算 hash 值并放在 cookie 中，使产生的 signedCookie 防篡改
  resave: true,//强制更新session
  saveUninitialized: false,//强制创建一个session，即使用户未登录
  cookie: {
    maxAge: config.session.maxAge//过期时间
  },
  store: new MongoStore({url: config.mongodb})
}));
```
这是代码，然后想知道怎么解决这个异常

**Comment by nswbmw** [comment]
`var MongoStore = require('connect-flash');` 
黑人问号？？？

**Comment by LeoCecilia** [comment]
哦哦，这是我看错啦，不过又有一个新的问题，就是我链接不了mongodb的数据库。
MongoError: failed to connect to server [localhost:27017] on first connect [Mong                                        oError: connect ECONNREFUSED 127.0.0.1:27017]
    at null.<anonymous> (F:\nBlog\node_modules\mongodb-core\lib\topologies\serve                                        r.js:328:35)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (F:\nBlog\node_modules\mongodb-core\lib\connection\pool.                                        js:274:12)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (F:\nBlog\node_modules\mongodb-core\lib\connection\con                                        nection.js:177:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
那这个要怎么解决啊
