### ISSUE TITLE
无法连接到mongodb

### ISSUE THREAD

**Issue by LeoCecilia** [nswbmw/N-blog#364]
MongoError: failed to connect to server [localhost:27017] on first connect [Mong oError: connect ECONNREFUSED 127.0.0.1:27017]
at null. (F:\nBlog\node_modules\mongodb-core\lib\topologies\serve r.js:328:35)
at emitOne (events.js:77:13)
at emit (events.js:169:7)
at null. (F:\nBlog\node_modules\mongodb-core\lib\connection\pool. js:274:12)
at g (events.js:260:16)
at emitTwo (events.js:87:13)
at emit (events.js:172:7)
at Socket. (F:\nBlog\node_modules\mongodb-core\lib\connection\con nection.js:177:49)
at Socket.g (events.js:260:16)
at emitOne (events.js:77:13)
at Socket.emit (events.js:169:7)
at emitErrorNT (net.js:1253:8)
at nextTickCallbackWith2Args (node.js:442:9)
at process._tickCallback (node.js:356:17)
这个要怎么解决

**Comment by nswbmw** [comment]
1. 检查 mongodb 启动了吗
2. 检查 mongodb 是否设置了密码

**Comment by LeoCecilia** [comment]
是使用那个mongod这个指令让它启动的嘛，但是显示没有这个指令，而且我在全局环境下安装了

**Comment by nswbmw** [comment]
把 mongdb 的 bin 目录加到环境变量里
