### ISSUE TITLE
ejs语法出错

### ISSUE THREAD

**Issue by LeoCecilia** [nswbmw/N-blog#365]
myblog listening on port 5000
Error: F:\nBlog\views\signup.ejs:1
 >> 1| <%- include('header') %>
    2|
    3| <div class="ui grid">
    4|   <div class="four wide column"></div>

Could not find matching close tag for "<%=".
    at F:\nBlog\node_modules\ejs\lib\ejs.js:595:19
    at Array.forEach (native)
    at Object.Template.generateSource (F:\nBlog\node_modules\ejs\lib\ejs.js:580:15)
    at Object.Template.compile (F:\nBlog\node_modules\ejs\lib\ejs.js:483:12)
    at Object.compile (F:\nBlog\node_modules\ejs\lib\ejs.js:338:16)
    at handleCache (F:\nBlog\node_modules\ejs\lib\ejs.js:181:18)
    at includeFile (F:\nBlog\node_modules\ejs\lib\ejs.js:239:10)
    at include (F:\nBlog\node_modules\ejs\lib\ejs.js:553:16)
    at eval (eval at <anonymous> (F:\nBlog\node_modules\ejs\lib\ejs.js:524:12), <anonymous>:9:17)
    at returnedFn (F:\nBlog\node_modules\ejs\lib\ejs.js:555:17)
    at tryHandleCache (F:\nBlog\node_modules\ejs\lib\ejs.js:203:34)
    at View.exports.renderFile [as engine] (F:\nBlog\node_modules\ejs\lib\ejs.js:412:10)
    at View.render (F:\nBlog\node_modules\express\lib\view.js:128:8)
    at tryRender (F:\nBlog\node_modules\express\lib\application.js:640:10)
    at EventEmitter.render (F:\nBlog\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (F:\nBlog\node_modules\express\lib\response.js:971:7)

想问一下这个要怎么解决呢，已经在index.js那里设置了`app.use('view engine','ejs')`

**Comment by nswbmw** [comment]
应该是 header.ejs 有问题，贴下代码

**Comment by LeoCecilia** [comment]
``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%=blog.title></title>
    <link rel="stylesheet" href="//cdn.bootcss.com/semantic-ui/2.1.8/semantic.min.css">
    <link rel="stylesheet" href="/css/style.css">
    <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/semantic-ui/2.1.8/semantic.min.js"></script>
  </head>
  <body>
      <%- include('comonents/nav') %>
      <%- include('comonents/nav-setting') %>
      <%- include('comonents/notification') %>

```

**Comment by LeoCecilia** [comment]
噢噢噢，我看到了
