### ISSUE TITLE
發表文章時報錯

### ISSUE THREAD

**Issue by LeoCecilia** [nswbmw/N-blog#370]
以下是我的代碼
model/post.js
``` javascript
exports.Post = mongolass.model('Post',{
  author: {type:Mongolass.Types.objectId},
  title: {type: 'string'},
  content: {type:'string'},
  pv: {type:'number'}//點擊量
});

//按創建時間降序來查看用戶文章列表
exports.Post.index({author:1,_id:-1}).exec();
```

route/post.js
``` javascript
  PostModel.create(post).then(function (result) {
    post = result.ops[0];
    req.flash('success','發表成功');
    res.redirect(`/posts/${post._id}`);
  }).catch(e=>{
    console.log(e);
    console.log(e.stack);
    next(e);
  });
});
```

然後應該是說，`Mongolass.Types.objectId`是一個對象，於是我就把他改成了type:'string'，這是可以上傳的，可是後來查看文章找不到數據，顯示文章不存在。這個要怎麽解決啊，然後就想問一下`Mongolass.Types.objectId`的作用是什麽啊，報錯信息如下

{ [Error: ($.author: "59253821526286ab4468e73c") ✖ (type: object)]
  validator: 'type',
  actual: '59253821526286ab4468e73c',
  expected: 
   { type: 
      AJS {
        _parent: [Object],
        _path: '$.author.type',
        _schema: {},
        _name: 'PostSchema' } },
  path: '$.author',
  schema: 'PostSchema',
  model: 'Post',
  plugin: 'MongolassSchema',
  type: 'beforeInsert',
  args: [] }
Error: ($.author: "59253821526286ab4468e73c") ✖ (type: object)
    at throwError (f:\nBlog\node_modules\another-json-schema\index.js:223:13)
    at validateType (f:\nBlog\node_modules\another-json-schema\index.js:163:7)
    at iterator (f:\nBlog\node_modules\another-json-schema\index.js:117:7)
    at iterator (f:\nBlog\node_modules\another-json-schema\index.js:133:29)
    at _validateObject (f:\nBlog\node_modules\another-json-schema\index.js:108:11)
    at _Schema.validate (f:\nBlog\node_modules\another-json-schema\index.js:38:10)
    at formatCreate (f:\nBlog\node_modules\mongolass\lib\schema.js:186:25)
    at f:\nBlog\node_modules\mongolass\lib\schema.js:93:27
    at Array.forEach (native)
    at Query.beforeInsert (f:\nBlog\node_modules\mongolass\lib\schema.js:93:12)
    at f:\nBlog\node_modules\mongolass\lib\query.js:146:44
    at next (native)
    at onFulfilled (f:\nBlog\node_modules\co\index.js:65:19)
    at f:\nBlog\node_modules\co\index.js:54:5
    at co (f:\nBlog\node_modules\co\index.js:50:10)
    at Query.execBeforePlugins (f:\nBlog\node_modules\mongolass\lib\query.js:142:10)
----- Mongolass error stack -----
Error
    at Model.insert (f:\nBlog\node_modules\mongolass\lib\query.js:108:16)
    at Object.module.exports.create (f:\nBlog\models\post.js:5:17)
    at f:\nBlog\routes\posts.js:38:13
    at Layer.handle [as handle_request] (f:\nBlog\node_modules\express\lib\router\layer.js:95:5)
    at next (f:\nBlog\node_modules\express\lib\router\route.js:137:13)
    at checkLogin (f:\nBlog\middleware\check.js:8:5)
    at Layer.handle [as handle_request] (f:\nBlog\node_modules\express\lib\router\layer.js:95:5)
    at next (f:\nBlog\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (f:\nBlog\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (f:\nBlog\node_modules\express\lib\router\layer.js:95:5)
    at f:\nBlog\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (f:\nBlog\node_modules\express\lib\router\index.js:335:12)
    at next (f:\nBlog\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (f:\nBlog\node_modules\express\lib\router\index.js:174:3)
    at router (f:\nBlog\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (f:\nBlog\node_modules\express\lib\router\layer.js:95:5)
Error: ($.author: "59253821526286ab4468e73c") ✖ (type: object)
    at throwError (f:\nBlog\node_modules\another-json-schema\index.js:223:13)
    at validateType (f:\nBlog\node_modules\another-json-schema\index.js:163:7)
    at iterator (f:\nBlog\node_modules\another-json-schema\index.js:117:7)
    at iterator (f:\nBlog\node_modules\another-json-schema\index.js:133:29)
    at _validateObject (f:\nBlog\node_modules\another-json-schema\index.js:108:11)
    at _Schema.validate (f:\nBlog\node_modules\another-json-schema\index.js:38:10)
    at formatCreate (f:\nBlog\node_modules\mongolass\lib\schema.js:186:25)
    at f:\nBlog\node_modules\mongolass\lib\schema.js:93:27
    at Array.forEach (native)
    at Query.beforeInsert (f:\nBlog\node_modules\mongolass\lib\schema.js:93:12)
    at f:\nBlog\node_modules\mongolass\lib\query.js:146:44
    at next (native)
    at onFulfilled (f:\nBlog\node_modules\co\index.js:65:19)
    at f:\nBlog\node_modules\co\index.js:54:5
    at co (f:\nBlog\node_modules\co\index.js:50:10)
    at Query.execBeforePlugins (f:\nBlog\node_modules\mongolass\lib\query.js:142:10)
----- Mongolass error stack -----
Error
    at Model.insert (f:\nBlog\node_modules\mongolass\lib\query.js:108:16)
    at Object.module.exports.create (f:\nBlog\models\post.js:5:17)
    at f:\nBlog\routes\posts.js:38:13
    at Layer.handle [as handle_request] (f:\nBlog\node_modules\express\lib\router\layer.js:95:5)
    at next (f:\nBlog\node_modules\express\lib\router\route.js:137:13)
    at checkLogin (f:\nBlog\middleware\check.js:8:5)
    at Layer.handle [as handle_request] (f:\nBlog\node_modules\express\lib\router\layer.js:95:5)
    at next (f:\nBlog\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (f:\nBlog\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (f:\nBlog\node_modules\express\lib\router\layer.js:95:5)
    at f:\nBlog\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (f:\nBlog\node_modules\express\lib\router\index.js:335:12)
    at next (f:\nBlog\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (f:\nBlog\node_modules\express\lib\router\index.js:174:3)
    at router (f:\nBlog\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (f:\nBlog\node_modules\express\lib\router\layer.js:95:5)

感覺是説我類型錯誤，但是沒看懂哪裏出錯

**Comment by LeoCecilia** [comment]
發現好像查看文件可以了耶

**Comment by nswbmw** [comment]
你清空数据库，再试下，不要来回改 type，认定一个，比如 type:Mongolass.Types.objectId 就可以

**Comment by LeoCecilia** [comment]
哦哦，好的
