### ISSUE TITLE
mongolass中的批量插入应该return什么？

### ISSUE THREAD

**Issue by littlesida** [nswbmw/N-blog#378]
在N-blog这个教程中，**users.js**中创建一个用户时return的是**exec**后的对象.
```  
create: function create(user) {
    return User.create(user).exec();
  }
```
请问，如果我想批量插入的话，我应该怎么做？由于是第一次接触mongodb，不是很熟悉，查看了您的**Mongolass——一个类 mongoose 的 MongoDB 驱动库**这篇文章后，去查看了mongoose的文档，发现mongoose是通过new一个Promise，然后使用forEach，最后返回promise的。[mongoose的create](http://www.nodeclass.com/api/mongoose.html#model_Model.create)。
当我尝试这样做时，
```
createMore: function createMore(students) {
    var result = [];
    students.forEach(function(student) {
        var t = Student.create(student).exec();
        result.push(t);
    });
    return result;
  },
```
出现如下错误信息
`----- Mongolass error stack -----
Error
    at Model.insert (/home/littlestar/shixun/node_modules/mongolass/lib/query.js:108:16)
    at /home/littlestar/shixun/models/students.js:12:25
    at Array.forEach (native)
    at Object.createMore (/home/littlestar/shixun/models/students.js:11:14)
`
因此，想请教一下，当要批量插入时，createMore这个函数应该如何实现呢？

**Comment by littlesida** [comment]
好的!非常感谢。
