### ISSUE TITLE
 TypeError: option expires is invalid 

### ISSUE THREAD

**Issue by meihuanyu** [nswbmw/N-blog#387]
TypeError: option expires is invalid
    at Object.serialize (/Users/app/Applications/myblog/node_modules/cookie/index.js:145:13)
    at setcookie (/Users/app/Applications/myblog/node_modules/express-session/index.js:636:21)
    at ServerResponse.<anonymous> (/Users/app/Applications/myblog/node_modules/express-session/index.js:242:7)
    at ServerResponse.writeHead (/Users/app/Applications/myblog/node_modules/on-headers/index.js:46:16)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:448:10)
    at writetop (/Users/app/Applications/myblog/node_modules/express-session/index.js:290:26)
    at ServerResponse.send (/Users/app/Applications/myblog/node_modules/express/lib/response.js:211:10)
    at /Users/app/Applications/myblog/routes/posts.js:9:9
    at Layer.handle [as handle_request] (/Users/app/Applications/myblog/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/app/Applications/myblog/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/app/Applications/myblog/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/app/Applications/myblog/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/app/Applications/myblog/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/app/Applications/myblog/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/app/Applications/myblog/node_modules/express/lib/router/index.js:47:12)

博主大大 你好。
在4-4-4的那里 刚刚写完所有的代码并且查了一遍  但是它就是疯狂的报这个错

res.send(req.flash());

跑到这句就报错

**Comment by nswbmw** [comment]
报错信息很明显啊~看下 express-session 中间件的 cookie.maxAge 设置的是否正确

**Comment by meihuanyu** [comment]
全部删除 重新来一遍解决了
