### ISSUE TITLE
博主大神，这个问题怎么解决啊。

### ISSUE THREAD

**Issue by gwbjx123** [nswbmw/N-blog#410]
TypeError: Cannot read property 'create' of undefined
    at Object.create (D:\学习\Express_Mongodb_blog\myblog\models\users.js:13:16)
    at D:\学习\Express_Mongodb_blog\myblog\routes\signup.js:63:13
    at Layer.handle [as handle_request] (D:\学习\Express_Mongodb_blog\myblog\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\学习\Express_Mongodb_blog\myblog\node_modules\express\lib\router\route.js:137:13)
    at checkNotLogin (D:\学习\Express_Mongodb_blog\myblog\middlewares\check.js:15:5)
    at Layer.handle [as handle_request] (D:\学习\Express_Mongodb_blog\myblog\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\学习\Express_Mongodb_blog\myblog\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\学习\Express_Mongodb_blog\myblog\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\学习\Express_Mongodb_blog\myblog\node_modules\express\lib\router\layer.js:95:5)
    at D:\学习\Express_Mongodb_blog\myblog\node_modules\express\lib\router\index.js:281:22
按博主的教程写的，实在是找不到问题原因了。

**Comment by nswbmw** [comment]
我猜你 lib/mongo.js 没有导出 User

**Comment by gwbjx123** [comment]
奇了怪了。
![image](https://user-images.githubusercontent.com/16699142/32730292-910c5f4e-c8c1-11e7-81e4-2a30ed005051.png)
这里原来有个空格，我回退了一下就好了。

实在太感谢您了！
