### ISSUE TITLE
4.9.3 主页与文章页出现的问题

### ISSUE THREAD

**Issue by ymwhat** [nswbmw/N-blog#414]
4.9.3 主页与文章页中出现的问题

您好！
调试中，请求的url是  http://localhost:3000/posts  这样的话，author为空，
代码：
router.get('/', function(req, res, next){
  const author = req.query.author
  console.log('author', author)
  PostModel.getPosts(author)
  .then(function(posts){ 
    //author为空，执行完getPosts后，then函数不会被执行，返回后直接执行catch，报错如下
    console.log("get...", posts)
    res.render('posts', {
      posts: posts
    })
  })
  .catch(next)
})

奇怪的是，这种情况下，无论访问/signin、/signup都会跳转到/posts，不知道是什么原因..
错误代码在这里： https://github.com/ymwhat/nbook
还请您指出错误，谢谢！

报错如下：
TypeError: Invalid objectId, got undefined
    at Model.find (/Users/yangmei/WebstormProjects/myblog/node_modules/mongolass/lib/query.js:104:16)
    at Object.getPosts (/Users/yangmei/WebstormProjects/myblog/models/posts.js:39:8)
    at /Users/yangmei/WebstormProjects/myblog/routes/posts.js:13:13
    at Layer.handle [as handle_request] (/Users/yangmei/WebstormProjects/myblog/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/yangmei/WebstormProjects/myblog/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/yangmei/WebstormProjects/myblog/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/yangmei/WebstormProjects/myblog/node_modules/express/lib/router/layer.js:95:5)
    at /Users/yangmei/WebstormProjects/myblog/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/yangmei/WebstormProjects/myblog/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/yangmei/WebstormProjects/myblog/node_modules/express/lib/router/index.js:275:10)

**Comment by 12454j** [comment]
Why
Talk to me

James Thornton
