### ISSUE TITLE
4.7注册页预览出错的问题解决办法

### ISSUE THREAD

**Issue by jhs1873** [nswbmw/N-blog#415]
### 4.7注册章节预览时的出错:

```html
Error: C:\Users\Administrator\Desktop\blog\views\signup.ejs:1
 >> 1| <%- include('header') %>

    2| 

    3| <div class="ui grid">

    4|   <div class="four wide column"></div>


C:\Users\Administrator\Desktop\blog\views\header.ejs:12
    10|   </head>

    11|   <body>

 >> 12|   <%- include('components/nav') %>

    13|   <%- include('components/nav-setting') %>

    14|   <%- include('components/notification') %>

Could not find include include file.
    at getIncludePath (C:\Users\Administrator\Desktop\blog\node_modules\ejs\lib\ejs.js:152:13)
    at includeFile (C:\Users\Administrator\Desktop\blog\node_modules\ejs\lib\ejs.js:258:19)
    at include (C:\Users\Administrator\Desktop\blog\node_modules\ejs\lib\ejs.js:578:16)
    at eval (eval at compile (C:\Users\Administrator\Desktop\blog\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:14:17)
    at returnedFn (C:\Users\Administrator\Desktop\blog\node_modules\ejs\lib\ejs.js:580:17)
    at include (C:\Users\Administrator\Desktop\blog\node_modules\ejs\lib\ejs.js:578:39)
    at eval (eval at compile (C:\Users\Administrator\Desktop\blog\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:9:17)
    at returnedFn (C:\Users\Administrator\Desktop\blog\node_modules\ejs\lib\ejs.js:580:17)
    at tryHandleCache (C:\Users\Administrator\Desktop\blog\node_modules\ejs\lib\ejs.js:223:34)
    at View.exports.renderFile [as engine] (C:\Users\Administrator\Desktop\blog\node_modules\ejs\lib\ejs.js:437:10)
```
### 错误原因
views/header.ejs 

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= blog.title %></title>
    <link rel="stylesheet" href="//cdn.bootcss.com/semantic-ui/2.1.8/semantic.min.css">
    <link rel="stylesheet" href="/css/style.css">
    <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/semantic-ui/2.1.8/semantic.min.js"></script>
  </head>
  <body>
  <%- include('components/nav') %>
  <%- include('components/nav-setting') %>
  <%- include('components/notification') %>
```

>引入外部资源时的路径,需要添加https:
>引入css时增加..

### 修改后:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= blog.title %></title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/semantic-ui/2.1.8/semantic.min.css">
    <link rel="stylesheet" href="../css/style.css">
    <script src="https://cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/semantic-ui/2.1.8/semantic.min.js"></script>
  </head>
  <body>
  <%- include('../components/nav') %>
  <%- include('../components/nav-setting') %>
  <%- include('../components/notification') %>
```

**Comment by Bennn123** [comment]
非常感谢！



常勇
三维软件工程师
15221561742
changyong@xuantech.cn
上海玄科计算技术有限公司
 
发件人： jhs1873
发送时间： 2017-11-22 11:18
收件人： nswbmw/N-blog
抄送： Subscribed
主题： [nswbmw/N-blog] 4.7注册页预览出错的问题解决办法 (#415)
4.7注册章节预览时的出错:
Error: C:\Users\Administrator\Desktop\blog\views\signup.ejs:1
 >> 1| <%- include('header') %>
    2| 
    3| <div class="ui grid">
    4|   <div class="four wide column"></div>
C:\Users\Administrator\Desktop\blog\views\header.ejs:12
    10|   </head>
    11|   <body>
 >> 12|   <%- include('components/nav') %>
    13|   <%- include('components/nav-setting') %>
    14|   <%- include('components/notification') %>
Could not find include include file.
    at getIncludePath (C:\Users\Administrator\Desktop\blog\node_modules\ejs\lib\ejs.js:152:13)
    at includeFile (C:\Users\Administrator\Desktop\blog\node_modules\ejs\lib\ejs.js:258:19)
    at include (C:\Users\Administrator\Desktop\blog\node_modules\ejs\lib\ejs.js:578:16)
    at eval (eval at compile (C:\Users\Administrator\Desktop\blog\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:14:17)
    at returnedFn (C:\Users\Administrator\Desktop\blog\node_modules\ejs\lib\ejs.js:580:17)
    at include (C:\Users\Administrator\Desktop\blog\node_modules\ejs\lib\ejs.js:578:39)
    at eval (eval at compile (C:\Users\Administrator\Desktop\blog\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:9:17)
    at returnedFn (C:\Users\Administrator\Desktop\blog\node_modules\ejs\lib\ejs.js:580:17)
    at tryHandleCache (C:\Users\Administrator\Desktop\blog\node_modules\ejs\lib\ejs.js:223:34)
    at View.exports.renderFile [as engine] (C:\Users\Administrator\Desktop\blog\node_modules\ejs\lib\ejs.js:437:10)
错误原因
views/header.ejs
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= blog.title %></title>
    <link rel="stylesheet" href="//cdn.bootcss.com/semantic-ui/2.1.8/semantic.min.css">
    <link rel="stylesheet" href="/css/style.css">
    <script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/semantic-ui/2.1.8/semantic.min.js"></script>
  </head>
  <body>
  <%- include('components/nav') %>
  <%- include('components/nav-setting') %>
  <%- include('components/notification') %>
引入外部资源时的路径,需要添加https:
引入css时增加..
修改后:
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= blog.title %></title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/semantic-ui/2.1.8/semantic.min.css">
    <link rel="stylesheet" href="../css/style.css">
    <script src="https://cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/semantic-ui/2.1.8/semantic.min.js"></script>
  </head>
  <body>
  <%- include('../components/nav') %>
  <%- include('../components/nav-setting') %>
  <%- include('../components/notification') %>
