### ISSUE TITLE
跟着书做完4.4节的时侯，发现运行不了，连接mongodb报错

### ISSUE THREAD

**Issue by oovwall** [nswbmw/N-blog#420]
错误提示如下：
```powershell
MacBook-Pro:myblog$ node index
myblog listening on port 3000

/Users/oovwall/GitHub/myblog/node_modules/mongodb/lib/mongo_client.js:421
          throw err
          ^
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOTFOUND localhost localhost:27017]
    at Pool.<anonymous> (/Users/oovwall/GitHub/myblog/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:125:13)
    at Pool.emit (events.js:221:7)
    at Connection.<anonymous> (/Users/oovwall/GitHub/myblog/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:326:30)
    at emitTwo (events.js:135:13)
    at Connection.emit (events.js:224:7)
    at Socket.<anonymous> (/Users/oovwall/GitHub/myblog/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:324:30)
    at emitOne (events.js:125:13)

```

在此说明几个前提：
1.  我已经用brew工具装好Mongodb了，并可以用Studio 3T成功连接。
2. 在读本书中好像没有提到创建数据库之类的，是不是漏了呢？

**Comment by oovwall** [comment]
已经找到答案，已经在SF中找到一样的问题，加一个Host解决，感谢作者的付出
SF问题地址：
[https://segmentfault.com/q/1010000007628327](https://segmentfault.com/q/1010000007628327)
