### ISSUE TITLE
4.7注册页预览user is not defined，nav-setting.ejs 中的user没有定义，是怎么回事？

### ISSUE THREAD

**Issue by Rudy24** [nswbmw/N-blog#422]
ReferenceError: E:\study\demo\Node\myblog\views\signup.ejs:1
 >> 1|  <%- include('header') %>

    2| <div class="ui grid">

    3|   <div class="four wide column"></div>

    4|   <div class="eight wide column">

E:\study\demo\Node\myblog\views\header.ejs:13
    11|   <body>

    12|   <%- include('./components/nav') %>

 >> 13|   <%- include('./components/nav-setting') %>

    14|   <%- include('./components/notification') %>

    15| 

E:\study\demo\Node\myblog\views\components\nav-setting.ejs:6
    4|       <i class="icon bars"></i>

    5|       <div class="menu">

 >> 6|         <% if (user) { %>

    7|           <a class="item" href="/posts?author=<%= user._id %>">个人主页</a>

    8|           <div class="divider"></div>

    9|           <a class="item" href="/posts/create">发表文章</a>

user is not defined
    at eval (eval at compile (E:\study\demo\Node\myblog\node_modules\_ejs@2.5.7@ejs\lib\ejs.js:549:12), <anonymous>:11:8)
    at returnedFn (E:\study\demo\Node\myblog\node_modules\_ejs@2.5.7@ejs\lib\ejs.js:580:17)
    at include (E:\study\demo\Node\myblog\node_modules\_ejs@2.5.7@ejs\lib\ejs.js:578:39)
    at eval (eval at compile (E:\study\demo\Node\myblog\node_modules\_ejs@2.5.7@ejs\lib\ejs.js:549:12), <anonymous>:17:17)
    at returnedFn (E:\study\demo\Node\myblog\node_modules\_ejs@2.5.7@ejs\lib\ejs.js:580:17)
    at include (E:\study\demo\Node\myblog\node_modules\_ejs@2.5.7@ejs\lib\ejs.js:578:39)
    at eval (eval at compile (E:\study\demo\Node\myblog\node_modules\_ejs@2.5.7@ejs\lib\ejs.js:549:12), <anonymous>:10:17)
    at returnedFn (E:\study\demo\Node\myblog\node_modules\_ejs@2.5.7@ejs\lib\ejs.js:580:17)
    at tryHandleCache (E:\study\demo\Node\myblog\node_modules\_ejs@2.5.7@ejs\lib\ejs.js:223:34)
    at View.exports.renderFile [as engine] (E:\study\demo\Node\myblog\node_modules\_ejs@2.5.7@ejs\lib\ejs.js:437:10)

**Comment by Rudy24** [comment]
知道了，把user 改成locals.user就可以了

**Comment by liuklk** [comment]
为什么一直会收到这个邮件呀




发自网易邮箱 iPhone 版
在2017年12月11日 19:37，nswbmw 写道：

Closed #422.

**Comment by nswbmw** [comment]
@liuklk 你应该 watch 了，如果不想收到这类提醒可以取消 watch :)

**Comment by Rudy24** [comment]
@nswbmw 

主文件 index.js 里面 res.locals.user 这里是有值的，但不知道为什么到了渲染模板里面就没有值了呢？
// 添加模板必需的三个变量
app.use(function (req, res, next) {
  res.locals.user = req.session.user;
  res.locals.success = req.flash('success').toString();
  res.locals.error = req.flash('error').toString();
  console.log(res.locals.user);
  next();
});

nav-setting.ejs

<div class="nav-setting">
  <div class="ui buttons">
    <div class="ui floating dropdown button">
      <i class="icon bars"></i>
      <div class="menu">
        <% if (locals.user) { %>
          <a class="item" href="/posts?author=<%= locals.user._id %>">个人主页</a>
          <div class="divider"></div>
          <a class="item" href="/posts/create">发表文章</a>
          <a class="item" href="/signout">登出</a>
        <% } else { %>
          <a class="item" href="/signin">登录</a>
          <a class="item" href="/signup">注册</a>
        <% } %>
      </div>
    </div>
  </div>
</div>

**Comment by nswbmw** [comment]
```
 <% if (locals.user) { %>
```

改成 

```
 <% if (user) { %>
```

**Comment by Rudy24** [comment]
@nswbmw 
改成user 后 直接 user is not defined
