### ISSUE TITLE
删除文章和删除留言时报错（Cannot convert undefined or null to object）

### ISSUE THREAD

**Issue by LeeRayno** [nswbmw/N-blog#432]
### 开发环境 
* node:  ``` 8.9.3```
* MongoDB:  ```3.6```
* Express:  ```4.16.2```
> 错误信息如下：
``` bash 
{ TypeError: Cannot convert undefined or null to object
    at Model.remove (D:\Practice\nodejs\myblog\node_modules\mongolass\lib\query.js:101:16)
    at Object.delPostById (D:\Practice\nodejs\myblog\models\posts.js:120:8)
    at D:\Practice\nodejs\myblog\routes\posts.js:171:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  op: 'remove',
  args: [ { _id: 5a6034ada4a68aebb8ccbe71 } ],
  model: 'Post',
  schema: 'PostSchema' } 
```
models/posts.js:120:8
``` bash
// 通过文章 id  删除一篇文章
  delPostById(postId) {
    return Post
      .remove({
        _id: postId
      })
      .exec()
      .then(function(res) {
        // 文章删除后,再删除该文章下的所有留言
        if (res.result.ok && res.result.n > 0) {
          return CommentModel.delCommentsByPostId(postId)
        }
      })
  }
```
routes/posts.js:171:17
``` bash
// GET /posts/:postId/remove 删除一篇文章
router.get('/:postId/remove', checkLogin, function(req, res, next) {
  const postId = req.params.postId
  const author = req.session.user._id

  PostModel.getRawPostById(postId)
    .then(function(post) {
      if (!post) {
        throw new Error('文章不存在')
      }
      if (post.author._id.toString() !== author.toString()) {
        throw new Error('没有权限')
      }
      PostModel.delPostById(postId)
        .then(function() {
          req.flash('success', '删除文章成功')
          // 删除成功后跳转到主页
          res.redirect('/posts')
        })
        .catch(next)
    })
})
```
#### 删除留言也报一样的错误信息。

**Comment by LeeRayno** [comment]
@nswbmw  4.1.0 感谢博主解答的这么积极。

**Comment by nswbmw** [comment]
看不出啥问题来，你代码提交到 github，给个链接我看下

**Comment by LeeRayno** [comment]
@nswbmw  这个是链接： https://github.com/LeeRayno/node-blog 谢谢！

**Comment by LeeRayno** [comment]
@nswbmw  跑的我得代码吗？不会是MongoDB 版本的问题吧。

**Comment by nswbmw** [comment]
我本地是  3.4.10，我下个 3.6.0+试试

**Comment by nswbmw** [comment]
```js
const mongodb = require('mongodb')

mongodb.MongoClient.connect('mongodb://localhost/myblog')
  .then((client) => {
    const db = client.db('myblog')
    const query = { _id: mongodb.ObjectId('5a606a1c9c350c0a0087196c') }
    // db.collection('posts').findOne(query).then(console.log) // ok
    db.collection('posts').remove(query) // error
      .then(console.log)
      .catch(console.error)
  })
```

报错，感觉跟 mongodb 这个模块有关，可能是个bug。

**Comment by LeeRayno** [comment]
好的，谢谢！

**Comment by LeeRayno** [comment]
@nswbmw  把 remove 换成 deleteOne 代码可以执行玩，但是数据库并不会真的删除这条数据。。。

**Comment by nswbmw** [comment]
mongolass 恰好那有个 bug。。可能粘贴复制忘了改了。我更新了下 https://github.com/nswbmw/N-blog/commit/1d08afa6338bdd075cd30aeade498425dedbd789
