### ISSUE TITLE
为什么你的项目跑不起来，总是报这个错误，好像数据库连接有问题

### ISSUE THREAD

**Issue by yt7649757** [nswbmw/N-blog#433]
> C:\Users\yt\Desktop\N-blog-master\node_modules\mongolass\lib\index.js:32
  async connect (url, opts) {
        ^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\yt\Desktop\N-blog-master\lib\mongo.js:2:19)
    at Module._compile (module.js:570:32)

**Comment by guobing1993** [comment]
node版本是啥

**Comment by guobing1993** [comment]
环境贴出来看下

**Comment by nswbmw** [comment]
node 升级到 8+

**Comment by yt7649757** [comment]
C:\Users\yt\Desktop\N-blog-master>node -v
v6.9.1

C:\Users\yt\Desktop\N-blog-master>express --version
4.15.5
