### ISSUE TITLE
4.4 部分 supervisor index之后一堆 Cannot find module 'xxx'

### ISSUE THREAD

**Issue by Hasaki1997** [nswbmw/N-blog#440]
我最后把我跟着敲的代码都删了 完全 ctrl+c 教程里面的代码 也npm i --save 了那一堆依赖,但是还是一堆 Cannot find module 'xxx'

下面是其中一个
```
module.js:545
    throw err;
    ^

Error: Cannot find module 'send'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/media/zhangguowei/DATA/create-react-apps/a-nocreate-react-app/myblog/node_modules/_serve-static@1.13.2@serve-static/index.js:20:12)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)

```

**Comment by Hasaki1997** [comment]
node v9.8.0
mongodb v3.6.3
express v4.16.0

**Comment by nswbmw** [comment]
删除 node_modules，重新 npm i

**Comment by Hasaki1997** [comment]
非常感谢!
