### ISSUE TITLE
依照教程写到日志这一章是报错了

### ISSUE THREAD

**Issue by gouxiwen** [nswbmw/N-blog#448]
按照教程引入依赖，使用了日志中间件以后，启动项目，报以下错误
~/myblog/node_modules/_express-winston@2.5.1@express-winston/index.js:120
    options.winstonInstance = options.winstonInstance || (new winston.Logger ({ transports: options.transports }));                                                             ^

TypeError: winston.Logger is not a constructor
    at Object.errorLogger (/Users/ex-gouxiwen001/Desktop/learnNode/myblog/node_modules/_express-winston@2.5.1@express-winston/index.js:120:59)
    at Object.<anonymous> (/Users/ex-gouxiwen001/Desktop/learnNode/myblog/index.js:61:24)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
求解答。

**Comment by nswbmw** [comment]
https://github.com/bithavoc/express-winston/issues/175
winston api 变了，参考这个 issue 改一下吧
