### ISSUE TITLE
日志问题TypeError: winston.Logger is not a constructor

### ISSUE THREAD

**Issue by YBFJ** [nswbmw/N-blog#450]
您好，打扰了，我在按照您的代码输入之后，一直出现TypeError: winston.Logger is not a constructor这个问题，查了网络网上表示because winston.Logger has been changed to winston.createLogger. Updating your code to use .createLogger should fix your problem.请问这个问题我应该如何解决，不好意思，麻烦您了~
node index
/Users/CMJ/Desktop/myblog/node_modules/express-winston/index.js:192
  options.winstonInstance = options.winstonInstance || new winston.Logger({ transports: options.transports })
                                                       ^

TypeError: winston.Logger is not a constructor
    at Object.logger (/Users/CMJ/Desktop/myblog/node_modules/express-winston/index.js:192:56)
    at Object.<anonymous> (/Users/CMJ/Desktop/myblog/index.js:60:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by nswbmw** [comment]
https://github.com/nswbmw/N-blog/issues/448
https://github.com/bithavoc/express-winston/issues/175

winston@3 api 有变化，教程版本是 winston@2

**Comment by YBFJ** [comment]
收到！谢谢您！！！
陈敏佳






在2018年07月23日 21:53，nswbmw<notifications@github.com> 写道：

#448
bithavoc/express-winston#175

winston@3 api 有变化，教程版本是 winston@2
