### ISSUE TITLE
mongolass使用中出错

### ISSUE THREAD

**Issue by wycnet** [nswbmw/N-blog#456]
下面是报错，请问这什么原因？
D:\vscodeProject\myblog\node_modules\mongolass\lib\index.js:32
  async connect (url, opts) {
        ^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\vscodeProject\myblog\lib\mongo.js:2:19)
    at Module._compile (module.js:570:32)

**Comment by nswbmw** [comment]
使用 node@8+
