### ISSUE TITLE
User.findOne(...).addCreatedAt is not a function

### ISSUE THREAD

**Issue by dreamsline** [nswbmw/N-blog#460]
```
TypeError: User.findOne(...).addCreatedAt is not a function
    at Object.getUserByName (F:\Front-end items\myblog\models\users.js:13:10)
    at F:\Front-end items\myblog\routes\signin.js:30:13
    at Layer.handle [as handle_request] (F:\Front-end items\myblog\node_modules\express\lib\router\layer.js:95:5)
    at next (F:\Front-end items\myblog\node_modules\express\lib\router\route.js:137:13)
    at checkNotLogin (F:\Front-end items\myblog\middlewares\check.js:15:5)
    at Layer.handle [as handle_request] (F:\Front-end items\myblog\node_modules\express\lib\router\layer.js:95:5)
    at next (F:\Front-end items\myblog\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (F:\Front-end items\myblog\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (F:\Front-end items\myblog\node_modules\express\lib\router\layer.js:95:5)
    at F:\Front-end items\myblog\node_modules\express\lib\router\index.js:281:22
```
在登录这一步出现问题了，之前没有问题。

**Comment by nswbmw** [comment]
你看一下有没有 `mongolass.plugin('addCreatedAt', {})` 注册 addCreatedAt

**Comment by dreamsline** [comment]
就是这个地方，已经解决了，谢谢。
