### ISSUE TITLE
我参照 wiki的教程 :第1章--一个简单的博客,做到用户注册就失败了

### ISSUE THREAD

**Issue by benno233** [nswbmw/N-blog#70]
新手 求助  折腾1天了 没发觉到哪里写的不对
代码在这里 https://github.com/benno233/nodeApp 
请切换到 分支 2 
错误信息如下
<pre>
D:\github-project\nodeApp\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\connection\base.js:242
        throw message;      
              ^
Error: Error setting TTL index on collection : sessions
    at D:\github-project\nodeApp\node_modules\connect-mongo\lib\connect-mongo.js:161:23
    at D:\github-project\nodeApp\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\db.js:1430:36
    at __executeInsertCommand (D:\github-project\nodeApp\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\db.js:1829:12)
    at Db._executeInsertCommand (D:\github-project\nodeApp\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\db.js:1930:5)
    at D:\github-project\nodeApp\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\db.js:1427:14
    at D:\github-project\nodeApp\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\db.js:1560:7
    at D:\github-project\nodeApp\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\cursor.js:162:16
    at commandHandler (D:\github-project\nodeApp\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\cursor.js:706:16)
    at D:\github-project\nodeApp\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\db.js:1806:9
    at Server.Base._callHandler (D:\github-project\nodeApp\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\connection\base.js:442:41)
</pre>

**Comment by ccysfn** [comment]
我也是同样的问题，不知如何是好，把login.ejs删除了也不行。
n大能现身说法吗?

**Comment by nswbmw** [comment]
mongodb 2.6.6 没有这个问题，3.0会有这个问题。

**Comment by ccysfn** [comment]
all ritght .

**Comment by benno233** [comment]
更换版本后ok

**Comment by hechuanhua** [comment]
我的3.2也出现这个问题，不切换版本怎么解决这个问题啊
