### ISSUE TITLE
启动之后报错

### ISSUE THREAD

**Issue by hiddaorear** [nswbmw/N-blog#72]
``` shell
git clone git@github:nswbmw/N-blog.git
sudo npm install
node app.js
```

初次访问时，可以正常访问。我点击了下一页，然后就不能正常访问了，每次启动都会报以下错误。
是否是Mongodb没有配置好？因为在按照wiki第一章，写代码时，没有跑起来，也出现问题，故我想试着跑一下源程序。

 环境虚拟机中安装的ubuntu，node app.js
Linux ubuntu 3.13.0-46-generic #77-Ubuntu SMP Mon Mar 2 18:26:13 UTC 2015 i686 i686 i686 GNU/Linux

以下为报错信息：

```
Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
morgan deprecated morgan(options): use morgan("default", options) instead app.js:27:9
morgan deprecated default format: use combined format app.js:27:9
express-session deprecated undefined resave option; provide resave option app.js:36:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option app.js:36:9
Express server listening on port 3000
/home/hid/N-blog/node_modules/connect-mongo/lib/connect-mongo.js:178
          throw err;
                ^
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/home/hid/N-blog/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:553:74)
    at emit (events.js:118:17)
    at null.<anonymous> (/home/hid/N-blog/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:140:15)
    at emit (events.js:110:17)
    at Socket.<anonymous> (/home/hid/N-blog/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:512:10)
    at Socket.emit (events.js:107:17)
    at net.js:436:14
    at process._tickCallback (node.js:343:11)
```

**Comment by jiji262** [comment]
这个错误是怎么回事

**Comment by CommanderXL** [comment]
前8行的提示是配置问题。

**Comment by CommanderXL** [comment]
你这个地方出现的错误是mongodb没有启动。。每次Mongodb非正常关闭的时候在它的那个文件夹里面有个mongod.lock要删除后重新启动。

**Comment by lizhengnacl** [comment]
@CommanderXL 每次启动blog下面就会出现mongod.lock， 是mongodb安装错误么？

**Comment by CommanderXL** [comment]
@lizhengnacl 不是安装错误。是mongodb自带的一个机制

**Comment by lizhengnacl** [comment]
@CommanderXL 可以启动app的时候，我也提示Failed to load c++ bson extension, using pure JS version错误啊。

**Comment by lizhengnacl** [comment]
@CommanderXL 可是启动app的时候，我也提示Failed to load c++ bson extension, using pure JS version错误啊。

**Comment by CommanderXL** [comment]
@lizhengnacl 这个是提示编译的问题，因为JS被发明用来解析HTML文件的，BSON是二进制数据，具体的配置方案你在网上搜下。

**Comment by lizhengnacl** [comment]
@CommanderXL 
```
D:\blog>set DEBUG=blog & node app.js
Failed to load c++ bson extension, using pure JS version
D:\blog\app.js:14
app.use(session({
   ^
TypeError: Cannot read property 'use' of undefined
    at Object.<anonymous> (D:\blog\app.js:14:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```
win32位。
就是这个错误提示。我在想是不是版本问题，正在下2.6.1试试。

**Comment by CommanderXL** [comment]
@lizhengnacl 这个地方坑比较多，比如app.use(session)的位置，还有可能是版本不同，调用的方法不一样。

**Comment by lazybusy** [comment]
版本问题，先把mongodb和connect-mongo更到最新版本，然后把app.js中session的配置改成
store: new MongoStore({
  url: 'mongodb://localhost/blog'
})

**Comment by zll5131609** [comment]
这个问题最后解决了吗 我也碰到这个问题

**Comment by nswbmw** [comment]
教程已更新，请参考最新教程，见 [readme](https://github.com/nswbmw/N-blog)。
