### ISSUE TITLE
安装mongodb后启动app，提示错误，是版本问题么？

### ISSUE THREAD

**Issue by lizhengnacl** [nswbmw/N-blog#75]
- 操作系统：windows 32位
- 安装版本：mongodb-win32-i386-2.6.1.zip

根目录下package.json为：
```
{
    "name": "blog",
    "version": "0.0.0",
    "private": true,
    "scripts": {
        "start": "node ./bin/www"
    },
    "dependencies": {
        "body-parser": "~1.12.0",
        "cookie-parser": "~1.3.4",
        "debug": "~2.1.1",
        "ejs": "~2.3.1",
        "express": "~4.12.2",
        "morgan": "~1.5.1",
        "serve-favicon": "~2.2.0",
        "mongodb": "1.4.15",
        "express-session": "1.9.1",
        "connect-mongo": "0.4.1"
    }
}
```

安装后， 启动app， DOS界面提示错误为：
```
D:\blog>node app.js
Failed to load c++ bson extension, using pure JS version
D:\blog\app.js:14
app.use(session({
   ^
TypeError: Cannot read property 'use' of undefined
    at Object.<anonymous> (D:\blog\app.js:14:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

```
各位大大帮帮忙，卡到这儿下面没法继续啦。

**Comment by rccoder** [comment]
你是不是没有在node_models里面安装Mongodb?
截止目前，我的package.json里面是这样的
```
{
  "name": "SmartBlog",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "body-parser": "~1.12.0",
    "connect-flash": "^0.1.1",
    "connect-mongo": "^0.8.0",
    "cookie-parser": "~1.3.4",
    "debug": "~2.1.1",
    "express": "~4.12.2",
    "express-session": "^1.11.1",
    "markdown": "^0.5.0",
    "mongodb": "^2.0.27",
    "morgan": "~1.5.1",
    "multer": "^0.1.8",
    "serve-favicon": "~2.2.0",
    "swig": "^1.4.2",
    "ueditor": "^1.1.1"
  }
}
```

**Comment by CommanderXL** [comment]
试试把app.use(session(...))写到紧挨着引入的模块后面

**Comment by nswbmw** [comment]
`var app = express();` 的定义要放到所有 `app.use` 的前面

**Comment by lizhengnacl** [comment]
@nswbmw  @CommanderXL 谢谢，我已经放弃在windows平台了。

**Comment by nswbmw** [comment]
@lizhengnacl 正确的选择
