### ISSUE TITLE
把路由控制器和实现路由功能的函数都放到 index.js 后，运行app报错

### ISSUE THREAD

**Issue by Elric-pp** [nswbmw/N-blog#81]
按照文章中改动app.js和index.js，./bin/www获取不到app
```
/home/pp/blog/bin/www:16
app.set('port', port);
    ^
TypeError: undefined is not a function
    at Object.<anonymous> (/home/pp/blog/bin/www:16:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by Sirormy** [comment]
>修改 index.js，在 app.get('/') 函数后添加一条路由规则：
app.get('/nswbmw', function (req, res) {
  res.send('hello,world!');
});

这句话作者写错了，应该改为以下：

修改 index.js，在 **router.get('/')** 函数后添加一条路由规则：
```js
router.get('/nswbmw', function (req, res) {
  res.send('hello,world!');
});
```

**Comment by zmh7057** [comment]
同问...

**Comment by meritozh** [comment]
@Elric-pp 你看下./bin/www的代码，`var app = require('../app');`这行引用了app模块，这就要求`app.js`必须有`module.exports`这行代码。所以你可以直接运行`node app.js`，或者保持原样，不更改结构也是可以的。
