### ISSUE TITLE
 在第1章中，做到会话支持时，访问报错：Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by qq137712630** [nswbmw/N-blog#93]
代码：

var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var ejs = require('ejs');
var session = require('express-session');
var MongoStore = require('connect-mongo')(session);
var flash = require('connect-flash');

var routes = require('./routes/index');
var settings = require('./settings');

var app = express();

// view engine setup
app.set('port', process.env.PORT || 3000);
app.set('views', path.join(__dirname, 'views'));
app.engine('.html', ejs.__express);
app.set('view engine', 'html');// app.set('view engine', 'ejs');

// uncomment after placing your favicon in /public
//app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));

app.use(session({
  secret: settings.cookieSecret,
  key: settings.db,//cookie name
  cookie: {maxAge: 1000 * 60 * 60 * 24 * 30},//30 days
  store: new MongoStore({
    db: settings.db,
    host: settings.host,
    port: settings.port
  })
}));

app.use(flash());
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

routes(app);

app.listen(app.get('port'), function() {
  console.log('Express server listening on port ' + app.get('port'));
});

日志：
D:\nodejspojo\mo-demo\nodejs-demo\node_modules\mongodb\lib\mongodb\connection\base.js:246
        throw message;
              ^
TypeError: Cannot read property 'length' of undefined
    at processResults (D:\nodejspojo\mo-demo\nodejs-demo\node_modules\mongodb\lib\mongodb\db.js:1603:31)
    at D:\nodejspojo\mo-demo\nodejs-demo\node_modules\mongodb\lib\mongodb\db.js:1641:20
    at D:\nodejspojo\mo-demo\nodejs-demo\node_modules\mongodb\lib\mongodb\db.js:1179:7
    at D:\nodejspojo\mo-demo\nodejs-demo\node_modules\mongodb\lib\mongodb\db.js:1912:9
    at Server.Base._callHandler (D:\nodejspojo\mo-demo\nodejs-demo\node_modules\mongodb\lib\mongodb\connection\base.js:4
48:41)
    at D:\nodejspojo\mo-demo\nodejs-demo\node_modules\mongodb\lib\mongodb\connection\server.js:481:18
    at MongoReply.parseBody (D:\nodejspojo\mo-demo\nodejs-demo\node_modules\mongodb\lib\mongodb\responses\mongo_reply.js
:68:5)
    at null.<anonymous> (D:\nodejspojo\mo-demo\nodejs-demo\node_modules\mongodb\lib\mongodb\connection\server.js:439:20)

    at emit (events.js:107:17)
    at null.<anonymous> (D:\nodejspojo\mo-demo\nodejs-demo\node_modules\mongodb\lib\mongodb\connection\connection_pool.j
s:201:13)
Program node app.js exited with code 1

求解

大概找到问题的出错范围了：

  store: new MongoStore({
    db: settings.db,
    host: settings.host,
    port: settings.port
  })

但还是要请教大家···

**Comment by qq137712630** [comment]
解决了，方法：
1、先把 ``` mongodb ```` 卸载了：
      d:\nodejspojo\mo-demo\nodejs-demo>npm uninstall mongodb
      unbuild mongodb@1.4.15
2、默认安装 ：

d:\nodejspojo\mo-demo\nodejs-demo>npm install mongodb --save
\


> bson@0.2.22 install d:\nodejspojo\mo-demo\nodejs-demo\node_modules\mongodb\node_modules
\bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)


d:\nodejspojo\mo-demo\nodejs-demo\node_modules\mongodb\node_modules\bson>if not defined n
pm_config_node_gyp (node "D:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules
\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild |)
-


> kerberos@0.0.11 install d:\nodejspojo\mo-demo\nodejs-demo\node_modules\mongodb\node_mod
ules\kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)


d:\nodejspojo\mo-demo\nodejs-demo\node_modules\mongodb\node_modules\kerberos>if not defin
ed npm_config_node_gyp (node "D:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_mod
ules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
mongodb@1.4.39 node_modules\mongodb
├── bson@0.2.22 (nan@1.8.4)
├── kerberos@0.0.11 (nan@1.8.4)
└── readable-stream@2.0.2 (process-nextick-args@1.0.2, isarray@0.0.1, inherits@2.0.1,
util-deprecate@1.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
